package com.example.upc.dataobject;

import com.example.upc.config.picConfig.PicMini;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class BillReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_report.id
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_report.enterprise_id
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_report.name
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_report.picture
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_report.date
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_report.operator
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_report.operator_ip
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_report.operator_time
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_report.id
     *
     * @return the value of bill_report.id
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_report.id
     *
     * @param id the value for bill_report.id
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_report.enterprise_id
     *
     * @return the value of bill_report.enterprise_id
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_report.enterprise_id
     *
     * @param enterpriseId the value for bill_report.enterprise_id
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_report.name
     *
     * @return the value of bill_report.name
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_report.name
     *
     * @param name the value for bill_report.name
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_report.picture
     *
     * @return the value of bill_report.picture
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_report.picture
     *
     * @param picture the value for bill_report.picture
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_report.date
     *
     * @return the value of bill_report.date
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_report.date
     *
     * @param date the value for bill_report.date
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_report.operator
     *
     * @return the value of bill_report.operator
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_report.operator
     *
     * @param operator the value for bill_report.operator
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_report.operator_ip
     *
     * @return the value of bill_report.operator_ip
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_report.operator_ip
     *
     * @param operatorIp the value for bill_report.operator_ip
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_report.operator_time
     *
     * @return the value of bill_report.operator_time
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_report.operator_time
     *
     * @param operatorTime the value for bill_report.operator_time
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}