package com.example.upc.dataobject;

public class CaseFiling {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.id
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.record_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String recordNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.record_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String recordPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.record_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String      recordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.record_to_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String recordToType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.record_from
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String recordFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.record_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.party_name
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String partyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.party_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String partyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.region
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.address
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.zip_code
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.licence_small_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String licenceSmallType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.punishment_time
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String punishmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.punishment_book_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String punishmentBookNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.id_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.legal_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.phone
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.base_information
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String baseInformation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.charge_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String chargePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.charge_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String chargeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.filing_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String filingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.reason
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.punishment_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private Integer punishmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.punishment_reason
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String punishmentReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.major_illegal_facts
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String majorIllegalFacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.punishment_result
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String punishmentResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.punishment_do_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String punishmentDoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.help_way
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String helpWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.products_control
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String productsControl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.police_where
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String policeWhere;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.is_in
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String isIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.punishment_where
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String punishmentWhere;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.do_suggestion
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String doSuggestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_filing.document
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    private String document;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.id
     *
     * @return the value of case_filing.id
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.id
     *
     * @param id the value for case_filing.id
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.record_number
     *
     * @return the value of case_filing.record_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getRecordNumber() {
        return recordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.record_number
     *
     * @param recordNumber the value for case_filing.record_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setRecordNumber(String recordNumber) {
        this.recordNumber = recordNumber == null ? null : recordNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.record_person
     *
     * @return the value of case_filing.record_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getRecordPerson() {
        return recordPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.record_person
     *
     * @param recordPerson the value for case_filing.record_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setRecordPerson(String recordPerson) {
        this.recordPerson = recordPerson == null ? null : recordPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.record_date
     *
     * @return the value of case_filing.record_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.record_date
     *
     * @param recordDate the value for case_filing.record_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setRecordDate(String recordDate) {
        this.recordDate = recordDate == null ? null : recordDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.record_to_type
     *
     * @return the value of case_filing.record_to_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getRecordToType() {
        return recordToType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.record_to_type
     *
     * @param recordToType the value for case_filing.record_to_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setRecordToType(String recordToType) {
        this.recordToType = recordToType == null ? null : recordToType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.record_from
     *
     * @return the value of case_filing.record_from
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getRecordFrom() {
        return recordFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.record_from
     *
     * @param recordFrom the value for case_filing.record_from
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setRecordFrom(String recordFrom) {
        this.recordFrom = recordFrom == null ? null : recordFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.record_type
     *
     * @return the value of case_filing.record_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.record_type
     *
     * @param recordType the value for case_filing.record_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setRecordType(String recordType) {
        this.recordType = recordType == null ? null : recordType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.party_name
     *
     * @return the value of case_filing.party_name
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPartyName() {
        return partyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.party_name
     *
     * @param partyName the value for case_filing.party_name
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPartyName(String partyName) {
        this.partyName = partyName == null ? null : partyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.party_person
     *
     * @return the value of case_filing.party_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPartyPerson() {
        return partyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.party_person
     *
     * @param partyPerson the value for case_filing.party_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPartyPerson(String partyPerson) {
        this.partyPerson = partyPerson == null ? null : partyPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.region
     *
     * @return the value of case_filing.region
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.region
     *
     * @param region the value for case_filing.region
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.address
     *
     * @return the value of case_filing.address
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.address
     *
     * @param address the value for case_filing.address
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.zip_code
     *
     * @return the value of case_filing.zip_code
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.zip_code
     *
     * @param zipCode the value for case_filing.zip_code
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.licence_small_type
     *
     * @return the value of case_filing.licence_small_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getLicenceSmallType() {
        return licenceSmallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.licence_small_type
     *
     * @param licenceSmallType the value for case_filing.licence_small_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setLicenceSmallType(String licenceSmallType) {
        this.licenceSmallType = licenceSmallType == null ? null : licenceSmallType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.punishment_time
     *
     * @return the value of case_filing.punishment_time
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPunishmentTime() {
        return punishmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.punishment_time
     *
     * @param punishmentTime the value for case_filing.punishment_time
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPunishmentTime(String punishmentTime) {
        this.punishmentTime = punishmentTime == null ? null : punishmentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.punishment_book_number
     *
     * @return the value of case_filing.punishment_book_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPunishmentBookNumber() {
        return punishmentBookNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.punishment_book_number
     *
     * @param punishmentBookNumber the value for case_filing.punishment_book_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPunishmentBookNumber(String punishmentBookNumber) {
        this.punishmentBookNumber = punishmentBookNumber == null ? null : punishmentBookNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.id_number
     *
     * @return the value of case_filing.id_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.id_number
     *
     * @param idNumber the value for case_filing.id_number
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.legal_person
     *
     * @return the value of case_filing.legal_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.legal_person
     *
     * @param legalPerson the value for case_filing.legal_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.phone
     *
     * @return the value of case_filing.phone
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.phone
     *
     * @param phone the value for case_filing.phone
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.base_information
     *
     * @return the value of case_filing.base_information
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getBaseInformation() {
        return baseInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.base_information
     *
     * @param baseInformation the value for case_filing.base_information
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setBaseInformation(String baseInformation) {
        this.baseInformation = baseInformation == null ? null : baseInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.charge_person
     *
     * @return the value of case_filing.charge_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getChargePerson() {
        return chargePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.charge_person
     *
     * @param chargePerson the value for case_filing.charge_person
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setChargePerson(String chargePerson) {
        this.chargePerson = chargePerson == null ? null : chargePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.charge_date
     *
     * @return the value of case_filing.charge_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getChargeDate() {
        return chargeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.charge_date
     *
     * @param chargeDate the value for case_filing.charge_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setChargeDate(String chargeDate) {
        this.chargeDate = chargeDate == null ? null : chargeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.filing_date
     *
     * @return the value of case_filing.filing_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getFilingDate() {
        return filingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.filing_date
     *
     * @param filingDate the value for case_filing.filing_date
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setFilingDate(String filingDate) {
        this.filingDate = filingDate == null ? null : filingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.reason
     *
     * @return the value of case_filing.reason
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.reason
     *
     * @param reason the value for case_filing.reason
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.punishment_type
     *
     * @return the value of case_filing.punishment_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public Integer getPunishmentType() {
        return punishmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.punishment_type
     *
     * @param punishmentType the value for case_filing.punishment_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPunishmentType(Integer punishmentType) {
        this.punishmentType = punishmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.punishment_reason
     *
     * @return the value of case_filing.punishment_reason
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPunishmentReason() {
        return punishmentReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.punishment_reason
     *
     * @param punishmentReason the value for case_filing.punishment_reason
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPunishmentReason(String punishmentReason) {
        this.punishmentReason = punishmentReason == null ? null : punishmentReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.major_illegal_facts
     *
     * @return the value of case_filing.major_illegal_facts
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getMajorIllegalFacts() {
        return majorIllegalFacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.major_illegal_facts
     *
     * @param majorIllegalFacts the value for case_filing.major_illegal_facts
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setMajorIllegalFacts(String majorIllegalFacts) {
        this.majorIllegalFacts = majorIllegalFacts == null ? null : majorIllegalFacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.punishment_result
     *
     * @return the value of case_filing.punishment_result
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPunishmentResult() {
        return punishmentResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.punishment_result
     *
     * @param punishmentResult the value for case_filing.punishment_result
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPunishmentResult(String punishmentResult) {
        this.punishmentResult = punishmentResult == null ? null : punishmentResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.punishment_do_type
     *
     * @return the value of case_filing.punishment_do_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPunishmentDoType() {
        return punishmentDoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.punishment_do_type
     *
     * @param punishmentDoType the value for case_filing.punishment_do_type
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPunishmentDoType(String punishmentDoType) {
        this.punishmentDoType = punishmentDoType == null ? null : punishmentDoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.help_way
     *
     * @return the value of case_filing.help_way
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getHelpWay() {
        return helpWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.help_way
     *
     * @param helpWay the value for case_filing.help_way
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setHelpWay(String helpWay) {
        this.helpWay = helpWay == null ? null : helpWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.products_control
     *
     * @return the value of case_filing.products_control
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getProductsControl() {
        return productsControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.products_control
     *
     * @param productsControl the value for case_filing.products_control
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setProductsControl(String productsControl) {
        this.productsControl = productsControl == null ? null : productsControl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.police_where
     *
     * @return the value of case_filing.police_where
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPoliceWhere() {
        return policeWhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.police_where
     *
     * @param policeWhere the value for case_filing.police_where
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPoliceWhere(String policeWhere) {
        this.policeWhere = policeWhere == null ? null : policeWhere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.is_in
     *
     * @return the value of case_filing.is_in
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getIsIn() {
        return isIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.is_in
     *
     * @param isIn the value for case_filing.is_in
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setIsIn(String isIn) {
        this.isIn = isIn == null ? null : isIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.punishment_where
     *
     * @return the value of case_filing.punishment_where
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getPunishmentWhere() {
        return punishmentWhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.punishment_where
     *
     * @param punishmentWhere the value for case_filing.punishment_where
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setPunishmentWhere(String punishmentWhere) {
        this.punishmentWhere = punishmentWhere == null ? null : punishmentWhere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.do_suggestion
     *
     * @return the value of case_filing.do_suggestion
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getDoSuggestion() {
        return doSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.do_suggestion
     *
     * @param doSuggestion the value for case_filing.do_suggestion
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setDoSuggestion(String doSuggestion) {
        this.doSuggestion = doSuggestion == null ? null : doSuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_filing.document
     *
     * @return the value of case_filing.document
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public String getDocument() {
        return document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_filing.document
     *
     * @param document the value for case_filing.document
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    public void setDocument(String document) {
        this.document = document == null ? null : document.trim();
    }
}