package com.example.upc.dataobject;

import java.util.Date;

public class CommitteeCheckOptAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check_opt_answer.id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check_opt_answer.committee_check_id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    private Integer committeeCheckId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check_opt_answer.committee_check_opt_id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    private Integer committeeCheckOptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check_opt_answer.answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check_opt_answer.operator
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check_opt_answer.operator_ip
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check_opt_answer.operator_time
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check_opt_answer.id
     *
     * @return the value of committee_check_opt_answer.id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check_opt_answer.id
     *
     * @param id the value for committee_check_opt_answer.id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check_opt_answer.committee_check_id
     *
     * @return the value of committee_check_opt_answer.committee_check_id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public Integer getCommitteeCheckId() {
        return committeeCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check_opt_answer.committee_check_id
     *
     * @param committeeCheckId the value for committee_check_opt_answer.committee_check_id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public void setCommitteeCheckId(Integer committeeCheckId) {
        this.committeeCheckId = committeeCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check_opt_answer.committee_check_opt_id
     *
     * @return the value of committee_check_opt_answer.committee_check_opt_id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public Integer getCommitteeCheckOptId() {
        return committeeCheckOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check_opt_answer.committee_check_opt_id
     *
     * @param committeeCheckOptId the value for committee_check_opt_answer.committee_check_opt_id
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public void setCommitteeCheckOptId(Integer committeeCheckOptId) {
        this.committeeCheckOptId = committeeCheckOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check_opt_answer.answer
     *
     * @return the value of committee_check_opt_answer.answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check_opt_answer.answer
     *
     * @param answer the value for committee_check_opt_answer.answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check_opt_answer.operator
     *
     * @return the value of committee_check_opt_answer.operator
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check_opt_answer.operator
     *
     * @param operator the value for committee_check_opt_answer.operator
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check_opt_answer.operator_ip
     *
     * @return the value of committee_check_opt_answer.operator_ip
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check_opt_answer.operator_ip
     *
     * @param operatorIp the value for committee_check_opt_answer.operator_ip
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check_opt_answer.operator_time
     *
     * @return the value of committee_check_opt_answer.operator_time
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check_opt_answer.operator_time
     *
     * @param operatorTime the value for committee_check_opt_answer.operator_time
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}