package com.example.upc.dataobject;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class CommitteeCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.id
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.enterprise_id
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.check_time
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.recorder
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private String recorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.represent_sign1
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private String representSign1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.represent_sign2
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private String representSign2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.represent_sign3
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private String representSign3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.operator
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.operator_ip
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column committee_check.operator_time
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.id
     *
     * @return the value of committee_check.id
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.id
     *
     * @param id the value for committee_check.id
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.enterprise_id
     *
     * @return the value of committee_check.enterprise_id
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.enterprise_id
     *
     * @param enterpriseId the value for committee_check.enterprise_id
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.check_time
     *
     * @return the value of committee_check.check_time
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.check_time
     *
     * @param checkTime the value for committee_check.check_time
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.recorder
     *
     * @return the value of committee_check.recorder
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public String getRecorder() {
        return recorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.recorder
     *
     * @param recorder the value for committee_check.recorder
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setRecorder(String recorder) {
        this.recorder = recorder == null ? null : recorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.represent_sign1
     *
     * @return the value of committee_check.represent_sign1
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public String getRepresentSign1() {
        return representSign1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.represent_sign1
     *
     * @param representSign1 the value for committee_check.represent_sign1
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setRepresentSign1(String representSign1) {
        this.representSign1 = representSign1 == null ? null : representSign1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.represent_sign2
     *
     * @return the value of committee_check.represent_sign2
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public String getRepresentSign2() {
        return representSign2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.represent_sign2
     *
     * @param representSign2 the value for committee_check.represent_sign2
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setRepresentSign2(String representSign2) {
        this.representSign2 = representSign2 == null ? null : representSign2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.represent_sign3
     *
     * @return the value of committee_check.represent_sign3
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public String getRepresentSign3() {
        return representSign3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.represent_sign3
     *
     * @param representSign3 the value for committee_check.represent_sign3
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setRepresentSign3(String representSign3) {
        this.representSign3 = representSign3 == null ? null : representSign3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.operator
     *
     * @return the value of committee_check.operator
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.operator
     *
     * @param operator the value for committee_check.operator
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.operator_ip
     *
     * @return the value of committee_check.operator_ip
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.operator_ip
     *
     * @param operatorIp the value for committee_check.operator_ip
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column committee_check.operator_time
     *
     * @return the value of committee_check.operator_time
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column committee_check.operator_time
     *
     * @param operatorTime the value for committee_check.operator_time
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}