package com.example.upc.dataobject;

import java.util.Date;

public class ExamTrainMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.name
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.industry
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.work_type
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer workType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.score
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.content_type
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.remark
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_train_material.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.id
     *
     * @return the value of exam_train_material.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.id
     *
     * @param id the value for exam_train_material.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.name
     *
     * @return the value of exam_train_material.name
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.name
     *
     * @param name the value for exam_train_material.name
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.industry
     *
     * @return the value of exam_train_material.industry
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.industry
     *
     * @param industry the value for exam_train_material.industry
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.work_type
     *
     * @return the value of exam_train_material.work_type
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.work_type
     *
     * @param workType the value for exam_train_material.work_type
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setWorkType(Integer workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.score
     *
     * @return the value of exam_train_material.score
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.score
     *
     * @param score the value for exam_train_material.score
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.content_type
     *
     * @return the value of exam_train_material.content_type
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.content_type
     *
     * @param contentType the value for exam_train_material.content_type
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.remark
     *
     * @return the value of exam_train_material.remark
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.remark
     *
     * @param remark the value for exam_train_material.remark
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.operator
     *
     * @return the value of exam_train_material.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.operator
     *
     * @param operator the value for exam_train_material.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.operate_time
     *
     * @return the value of exam_train_material.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.operate_time
     *
     * @param operateTime the value for exam_train_material.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_train_material.operate_ip
     *
     * @return the value of exam_train_material.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_train_material.operate_ip
     *
     * @param operateIp the value for exam_train_material.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}