package com.example.upc.dataobject;

import java.util.Date;

public class FormatOriginFood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_food.id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_food.enterprise_id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_food.enterprise_name
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_food.area_id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_food.type
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_food.operator
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_food.operator_ip
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_food.operator_time
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_food.id
     *
     * @return the value of format_origin_food.id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_food.id
     *
     * @param id the value for format_origin_food.id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_food.enterprise_id
     *
     * @return the value of format_origin_food.enterprise_id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_food.enterprise_id
     *
     * @param enterpriseId the value for format_origin_food.enterprise_id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_food.enterprise_name
     *
     * @return the value of format_origin_food.enterprise_name
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_food.enterprise_name
     *
     * @param enterpriseName the value for format_origin_food.enterprise_name
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_food.area_id
     *
     * @return the value of format_origin_food.area_id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_food.area_id
     *
     * @param areaId the value for format_origin_food.area_id
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_food.type
     *
     * @return the value of format_origin_food.type
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_food.type
     *
     * @param type the value for format_origin_food.type
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_food.operator
     *
     * @return the value of format_origin_food.operator
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_food.operator
     *
     * @param operator the value for format_origin_food.operator
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_food.operator_ip
     *
     * @return the value of format_origin_food.operator_ip
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_food.operator_ip
     *
     * @param operatorIp the value for format_origin_food.operator_ip
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_food.operator_time
     *
     * @return the value of format_origin_food.operator_time
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_food.operator_time
     *
     * @param operatorTime the value for format_origin_food.operator_time
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}