package com.example.upc.dataobject;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class FormatLeaveSample {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.id
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.unit
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    private Integer unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.area
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.type
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
//    @NotBlank(message = "就餐类型不能为空")
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.date
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    @NotNull(message = "就餐日期不能为空")
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.meal
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    @NotBlank(message = "餐次不能为空")
    private String meal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.matter
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
//    @NotBlank(message = "事项不能为空")
    private String matter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.number
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    @NotBlank(message = "就餐人数不能为空")
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.person
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
//    @NotBlank(message = "操作人不能为空")
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.document
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    private String document;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.operator
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.operator_ip
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_leave_sample.operator_time
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.id
     *
     * @return the value of format_leave_sample.id
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.id
     *
     * @param id the value for format_leave_sample.id
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.unit
     *
     * @return the value of format_leave_sample.unit
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.unit
     *
     * @param unit the value for format_leave_sample.unit
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.area
     *
     * @return the value of format_leave_sample.area
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.area
     *
     * @param area the value for format_leave_sample.area
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.type
     *
     * @return the value of format_leave_sample.type
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.type
     *
     * @param type the value for format_leave_sample.type
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.date
     *
     * @return the value of format_leave_sample.date
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.date
     *
     * @param date the value for format_leave_sample.date
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.meal
     *
     * @return the value of format_leave_sample.meal
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public String getMeal() {
        return meal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.meal
     *
     * @param meal the value for format_leave_sample.meal
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setMeal(String meal) {
        this.meal = meal == null ? null : meal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.matter
     *
     * @return the value of format_leave_sample.matter
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public String getMatter() {
        return matter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.matter
     *
     * @param matter the value for format_leave_sample.matter
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setMatter(String matter) {
        this.matter = matter == null ? null : matter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.number
     *
     * @return the value of format_leave_sample.number
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.number
     *
     * @param number the value for format_leave_sample.number
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.person
     *
     * @return the value of format_leave_sample.person
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.person
     *
     * @param person the value for format_leave_sample.person
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.document
     *
     * @return the value of format_leave_sample.document
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public String getDocument() {
        return document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.document
     *
     * @param document the value for format_leave_sample.document
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setDocument(String document) {
        this.document = document == null ? null : document.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.operator
     *
     * @return the value of format_leave_sample.operator
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.operator
     *
     * @param operator the value for format_leave_sample.operator
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.operator_ip
     *
     * @return the value of format_leave_sample.operator_ip
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.operator_ip
     *
     * @param operatorIp the value for format_leave_sample.operator_ip
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_leave_sample.operator_time
     *
     * @return the value of format_leave_sample.operator_time
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_leave_sample.operator_time
     *
     * @param operatorTime the value for format_leave_sample.operator_time
     *
     * @mbg.generated Fri Sep 20 15:40:27 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}