package com.example.upc.dataobject;

import java.util.Date;

public class FormatQualityTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_quality_time.id
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_quality_time.seq
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_quality_time.name
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_quality_time.date
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_quality_time.operator
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_quality_time.operator_ip
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_quality_time.operator_time
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_quality_time.id
     *
     * @return the value of format_quality_time.id
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_quality_time.id
     *
     * @param id the value for format_quality_time.id
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_quality_time.seq
     *
     * @return the value of format_quality_time.seq
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_quality_time.seq
     *
     * @param seq the value for format_quality_time.seq
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_quality_time.name
     *
     * @return the value of format_quality_time.name
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_quality_time.name
     *
     * @param name the value for format_quality_time.name
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_quality_time.date
     *
     * @return the value of format_quality_time.date
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_quality_time.date
     *
     * @param date the value for format_quality_time.date
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_quality_time.operator
     *
     * @return the value of format_quality_time.operator
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_quality_time.operator
     *
     * @param operator the value for format_quality_time.operator
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_quality_time.operator_ip
     *
     * @return the value of format_quality_time.operator_ip
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_quality_time.operator_ip
     *
     * @param operatorIp the value for format_quality_time.operator_ip
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_quality_time.operator_time
     *
     * @return the value of format_quality_time.operator_time
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_quality_time.operator_time
     *
     * @param operatorTime the value for format_quality_time.operator_time
     *
     * @mbg.generated Thu Jul 11 11:22:51 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}