package com.example.upc.dataobject;

import java.util.Date;

public class GridPoints {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_points.id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_points.area_id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_points.enterprise_id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_points.point
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    private String point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_points.operate_time
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_points.operator
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_points.operate_ip
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_points.id
     *
     * @return the value of grid_points.id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_points.id
     *
     * @param id the value for grid_points.id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_points.area_id
     *
     * @return the value of grid_points.area_id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_points.area_id
     *
     * @param areaId the value for grid_points.area_id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_points.enterprise_id
     *
     * @return the value of grid_points.enterprise_id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_points.enterprise_id
     *
     * @param enterpriseId the value for grid_points.enterprise_id
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_points.point
     *
     * @return the value of grid_points.point
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_points.point
     *
     * @param point the value for grid_points.point
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public void setPoint(String point) {
        this.point = point == null ? null : point.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_points.operate_time
     *
     * @return the value of grid_points.operate_time
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_points.operate_time
     *
     * @param operateTime the value for grid_points.operate_time
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_points.operator
     *
     * @return the value of grid_points.operator
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_points.operator
     *
     * @param operator the value for grid_points.operator
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_points.operate_ip
     *
     * @return the value of grid_points.operate_ip
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_points.operate_ip
     *
     * @param operateIp the value for grid_points.operate_ip
     *
     * @mbg.generated Tue Aug 13 11:08:39 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}