package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class InspectForceDecision {
    private Integer id;
    private Integer parentId;
    private String forceNumber;
    @NotBlank(message = ("当事人不能为空"))
    private String concernedPerson;
    private String mainQualification;
    private String registrationNumber;
    private String address;
    private String header;
    private String idNumber;
    private String phoneNumber;
    private String ortherContact;
    @NotBlank(message = ("行为不能为空"))
    private String behavior;
    private String violationRegulations;
    private String accordingLaw;
    private String lawProvisions;
    private String lawTerm;
    private String lawItem;
    @NotBlank(message = ("文书编号不能为空"))
    private String fileNumber;
    private String forceMeasure;
    @NotBlank(message = ("地点不能为空"))
    private String forceMeasureAddress;
    @NotBlank(message = ("强制措施期限不能为空"))
    private String forceDate;
    private String saveCondition;
    @NotBlank(message = ("复议日不能为空"))
    private String applyReconsideration;
    private String reconsiderationDepartment;
    @NotNull(message = ("诉讼日期不能为空"))
    private Date applyLitigation;
    private String litigationDepartment;
    private String contectPerson;
    private String contectPhone;
    private Date operateTime;
    private String operateIp;
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.id
     *
     * @return the value of inspect_force_decision.id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.id
     *
     * @param id the value for inspect_force_decision.id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.parent_id
     *
     * @return the value of inspect_force_decision.parent_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.parent_id
     *
     * @param parentId the value for inspect_force_decision.parent_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.force_number
     *
     * @return the value of inspect_force_decision.force_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getForceNumber() {
        return forceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.force_number
     *
     * @param forceNumber the value for inspect_force_decision.force_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setForceNumber(String forceNumber) {
        this.forceNumber = forceNumber == null ? null : forceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.concerned_person
     *
     * @return the value of inspect_force_decision.concerned_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getConcernedPerson() {
        return concernedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.concerned_person
     *
     * @param concernedPerson the value for inspect_force_decision.concerned_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setConcernedPerson(String concernedPerson) {
        this.concernedPerson = concernedPerson == null ? null : concernedPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.main_qualification
     *
     * @return the value of inspect_force_decision.main_qualification
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getMainQualification() {
        return mainQualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.main_qualification
     *
     * @param mainQualification the value for inspect_force_decision.main_qualification
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setMainQualification(String mainQualification) {
        this.mainQualification = mainQualification == null ? null : mainQualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.registration_number
     *
     * @return the value of inspect_force_decision.registration_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.registration_number
     *
     * @param registrationNumber the value for inspect_force_decision.registration_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber == null ? null : registrationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.address
     *
     * @return the value of inspect_force_decision.address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.address
     *
     * @param address the value for inspect_force_decision.address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.header
     *
     * @return the value of inspect_force_decision.header
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.header
     *
     * @param header the value for inspect_force_decision.header
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.id_number
     *
     * @return the value of inspect_force_decision.id_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.id_number
     *
     * @param idNumber the value for inspect_force_decision.id_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.phone_number
     *
     * @return the value of inspect_force_decision.phone_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.phone_number
     *
     * @param phoneNumber the value for inspect_force_decision.phone_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.orther_contact
     *
     * @return the value of inspect_force_decision.orther_contact
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOrtherContact() {
        return ortherContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.orther_contact
     *
     * @param ortherContact the value for inspect_force_decision.orther_contact
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOrtherContact(String ortherContact) {
        this.ortherContact = ortherContact == null ? null : ortherContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.behavior
     *
     * @return the value of inspect_force_decision.behavior
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.behavior
     *
     * @param behavior the value for inspect_force_decision.behavior
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setBehavior(String behavior) {
        this.behavior = behavior == null ? null : behavior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.violation_regulations
     *
     * @return the value of inspect_force_decision.violation_regulations
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getViolationRegulations() {
        return violationRegulations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.violation_regulations
     *
     * @param violationRegulations the value for inspect_force_decision.violation_regulations
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setViolationRegulations(String violationRegulations) {
        this.violationRegulations = violationRegulations == null ? null : violationRegulations.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.according_law
     *
     * @return the value of inspect_force_decision.according_law
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getAccordingLaw() {
        return accordingLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.according_law
     *
     * @param accordingLaw the value for inspect_force_decision.according_law
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setAccordingLaw(String accordingLaw) {
        this.accordingLaw = accordingLaw == null ? null : accordingLaw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.law_provisions
     *
     * @return the value of inspect_force_decision.law_provisions
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getLawProvisions() {
        return lawProvisions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.law_provisions
     *
     * @param lawProvisions the value for inspect_force_decision.law_provisions
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setLawProvisions(String lawProvisions) {
        this.lawProvisions = lawProvisions == null ? null : lawProvisions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.law_term
     *
     * @return the value of inspect_force_decision.law_term
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getLawTerm() {
        return lawTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.law_term
     *
     * @param lawTerm the value for inspect_force_decision.law_term
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setLawTerm(String lawTerm) {
        this.lawTerm = lawTerm == null ? null : lawTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.law_item
     *
     * @return the value of inspect_force_decision.law_item
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getLawItem() {
        return lawItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.law_item
     *
     * @param lawItem the value for inspect_force_decision.law_item
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setLawItem(String lawItem) {
        this.lawItem = lawItem == null ? null : lawItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.file_number
     *
     * @return the value of inspect_force_decision.file_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getFileNumber() {
        return fileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.file_number
     *
     * @param fileNumber the value for inspect_force_decision.file_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setFileNumber(String fileNumber) {
        this.fileNumber = fileNumber == null ? null : fileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.force_measure
     *
     * @return the value of inspect_force_decision.force_measure
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getForceMeasure() {
        return forceMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.force_measure
     *
     * @param forceMeasure the value for inspect_force_decision.force_measure
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setForceMeasure(String forceMeasure) {
        this.forceMeasure = forceMeasure == null ? null : forceMeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.force_measure_address
     *
     * @return the value of inspect_force_decision.force_measure_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getForceMeasureAddress() {
        return forceMeasureAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.force_measure_address
     *
     * @param forceMeasureAddress the value for inspect_force_decision.force_measure_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setForceMeasureAddress(String forceMeasureAddress) {
        this.forceMeasureAddress = forceMeasureAddress == null ? null : forceMeasureAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.force_date
     *
     * @return the value of inspect_force_decision.force_date
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getForceDate() {
        return forceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.force_date
     *
     * @param forceDate the value for inspect_force_decision.force_date
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setForceDate(String forceDate) {
        this.forceDate = forceDate == null ? null : forceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.save_condition
     *
     * @return the value of inspect_force_decision.save_condition
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getSaveCondition() {
        return saveCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.save_condition
     *
     * @param saveCondition the value for inspect_force_decision.save_condition
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setSaveCondition(String saveCondition) {
        this.saveCondition = saveCondition == null ? null : saveCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.apply_reconsideration
     *
     * @return the value of inspect_force_decision.apply_reconsideration
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getApplyReconsideration() {
        return applyReconsideration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.apply_reconsideration
     *
     * @param applyReconsideration the value for inspect_force_decision.apply_reconsideration
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setApplyReconsideration(String applyReconsideration) {
        this.applyReconsideration = applyReconsideration == null ? null : applyReconsideration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.reconsideration_department
     *
     * @return the value of inspect_force_decision.reconsideration_department
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getReconsiderationDepartment() {
        return reconsiderationDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.reconsideration_department
     *
     * @param reconsiderationDepartment the value for inspect_force_decision.reconsideration_department
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setReconsiderationDepartment(String reconsiderationDepartment) {
        this.reconsiderationDepartment = reconsiderationDepartment == null ? null : reconsiderationDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.apply_litigation
     *
     * @return the value of inspect_force_decision.apply_litigation
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getApplyLitigation() {
        return applyLitigation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.apply_litigation
     *
     * @param applyLitigation the value for inspect_force_decision.apply_litigation
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setApplyLitigation(Date applyLitigation) {
        this.applyLitigation = applyLitigation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.litigation_department
     *
     * @return the value of inspect_force_decision.litigation_department
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getLitigationDepartment() {
        return litigationDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.litigation_department
     *
     * @param litigationDepartment the value for inspect_force_decision.litigation_department
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setLitigationDepartment(String litigationDepartment) {
        this.litigationDepartment = litigationDepartment == null ? null : litigationDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.contect_person
     *
     * @return the value of inspect_force_decision.contect_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getContectPerson() {
        return contectPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.contect_person
     *
     * @param contectPerson the value for inspect_force_decision.contect_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setContectPerson(String contectPerson) {
        this.contectPerson = contectPerson == null ? null : contectPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.contect_phone
     *
     * @return the value of inspect_force_decision.contect_phone
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getContectPhone() {
        return contectPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.contect_phone
     *
     * @param contectPhone the value for inspect_force_decision.contect_phone
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setContectPhone(String contectPhone) {
        this.contectPhone = contectPhone == null ? null : contectPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.operate_time
     *
     * @return the value of inspect_force_decision.operate_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.operate_time
     *
     * @param operateTime the value for inspect_force_decision.operate_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.operate_ip
     *
     * @return the value of inspect_force_decision.operate_ip
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.operate_ip
     *
     * @param operateIp the value for inspect_force_decision.operate_ip
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_force_decision.operator
     *
     * @return the value of inspect_force_decision.operator
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_force_decision.operator
     *
     * @param operator the value for inspect_force_decision.operator
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}