package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import java.util.Date;

public class InspectBookRecord {
    private Integer id;
    private Integer parentId;
    private String checkCause;
    @NotBlank(message = "当事人信息不能为空")
    private String party;
    private String mainQualification;
    private String registrationNumber;
    private String address;
    private String header;
    private String idNumber;
    private String phoneNumber;
    private String ortherContact;
    private String contactAddress;
    @NotBlank(message = "检查人不能不为空")
    private String examiner;
    private String enforcementNumber;
    private String lawEnforcement;
    private Date checkTimeFrom;
    private Date checkTimeTo;
    private String checkAddress;
    private String presentSituation;
    private Integer applyAvoid;
    private String witnessName;
    private String witnessId;
    private String informParties;
    private String statement;
    private String sceneCondition;
    private String firstEnforcer;
    private String secondEnforcer;
    private Date recorderTime;
    private Date operateTime;
    private String operateIp;
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.id
     *
     * @return the value of inspect_book_record.id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.id
     *
     * @param id the value for inspect_book_record.id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.parent_id
     *
     * @return the value of inspect_book_record.parent_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.parent_id
     *
     * @param parentId the value for inspect_book_record.parent_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.check_cause
     *
     * @return the value of inspect_book_record.check_cause
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getCheckCause() {
        return checkCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.check_cause
     *
     * @param checkCause the value for inspect_book_record.check_cause
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setCheckCause(String checkCause) {
        this.checkCause = checkCause == null ? null : checkCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.party
     *
     * @return the value of inspect_book_record.party
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.party
     *
     * @param party the value for inspect_book_record.party
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setParty(String party) {
        this.party = party == null ? null : party.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.main_qualification
     *
     * @return the value of inspect_book_record.main_qualification
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getMainQualification() {
        return mainQualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.main_qualification
     *
     * @param mainQualification the value for inspect_book_record.main_qualification
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setMainQualification(String mainQualification) {
        this.mainQualification = mainQualification == null ? null : mainQualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.registration_number
     *
     * @return the value of inspect_book_record.registration_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.registration_number
     *
     * @param registrationNumber the value for inspect_book_record.registration_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber == null ? null : registrationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.address
     *
     * @return the value of inspect_book_record.address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.address
     *
     * @param address the value for inspect_book_record.address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.header
     *
     * @return the value of inspect_book_record.header
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.header
     *
     * @param header the value for inspect_book_record.header
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.id_number
     *
     * @return the value of inspect_book_record.id_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.id_number
     *
     * @param idNumber the value for inspect_book_record.id_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.phone_number
     *
     * @return the value of inspect_book_record.phone_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.phone_number
     *
     * @param phoneNumber the value for inspect_book_record.phone_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.orther_contact
     *
     * @return the value of inspect_book_record.orther_contact
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOrtherContact() {
        return ortherContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.orther_contact
     *
     * @param ortherContact the value for inspect_book_record.orther_contact
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOrtherContact(String ortherContact) {
        this.ortherContact = ortherContact == null ? null : ortherContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.contact_address
     *
     * @return the value of inspect_book_record.contact_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.contact_address
     *
     * @param contactAddress the value for inspect_book_record.contact_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.examiner
     *
     * @return the value of inspect_book_record.examiner
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getExaminer() {
        return examiner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.examiner
     *
     * @param examiner the value for inspect_book_record.examiner
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setExaminer(String examiner) {
        this.examiner = examiner == null ? null : examiner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.enforcement_number
     *
     * @return the value of inspect_book_record.enforcement_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getEnforcementNumber() {
        return enforcementNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.enforcement_number
     *
     * @param enforcementNumber the value for inspect_book_record.enforcement_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setEnforcementNumber(String enforcementNumber) {
        this.enforcementNumber = enforcementNumber == null ? null : enforcementNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.law_enforcement
     *
     * @return the value of inspect_book_record.law_enforcement
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getLawEnforcement() {
        return lawEnforcement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.law_enforcement
     *
     * @param lawEnforcement the value for inspect_book_record.law_enforcement
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setLawEnforcement(String lawEnforcement) {
        this.lawEnforcement = lawEnforcement == null ? null : lawEnforcement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.check_time_from
     *
     * @return the value of inspect_book_record.check_time_from
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getCheckTimeFrom() {
        return checkTimeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.check_time_from
     *
     * @param checkTimeFrom the value for inspect_book_record.check_time_from
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setCheckTimeFrom(Date checkTimeFrom) {
        this.checkTimeFrom = checkTimeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.check_time_to
     *
     * @return the value of inspect_book_record.check_time_to
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getCheckTimeTo() {
        return checkTimeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.check_time_to
     *
     * @param checkTimeTo the value for inspect_book_record.check_time_to
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setCheckTimeTo(Date checkTimeTo) {
        this.checkTimeTo = checkTimeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.check_address
     *
     * @return the value of inspect_book_record.check_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getCheckAddress() {
        return checkAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.check_address
     *
     * @param checkAddress the value for inspect_book_record.check_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setCheckAddress(String checkAddress) {
        this.checkAddress = checkAddress == null ? null : checkAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.present_situation
     *
     * @return the value of inspect_book_record.present_situation
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getPresentSituation() {
        return presentSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.present_situation
     *
     * @param presentSituation the value for inspect_book_record.present_situation
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setPresentSituation(String presentSituation) {
        this.presentSituation = presentSituation == null ? null : presentSituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.apply_avoid
     *
     * @return the value of inspect_book_record.apply_avoid
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getApplyAvoid() {
        return applyAvoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.apply_avoid
     *
     * @param applyAvoid the value for inspect_book_record.apply_avoid
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setApplyAvoid(Integer applyAvoid) {
        this.applyAvoid = applyAvoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.witness_name
     *
     * @return the value of inspect_book_record.witness_name
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getWitnessName() {
        return witnessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.witness_name
     *
     * @param witnessName the value for inspect_book_record.witness_name
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setWitnessName(String witnessName) {
        this.witnessName = witnessName == null ? null : witnessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.witness_id
     *
     * @return the value of inspect_book_record.witness_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getWitnessId() {
        return witnessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.witness_id
     *
     * @param witnessId the value for inspect_book_record.witness_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setWitnessId(String witnessId) {
        this.witnessId = witnessId == null ? null : witnessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.inform_parties
     *
     * @return the value of inspect_book_record.inform_parties
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getInformParties() {
        return informParties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.inform_parties
     *
     * @param informParties the value for inspect_book_record.inform_parties
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setInformParties(String informParties) {
        this.informParties = informParties == null ? null : informParties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.statement
     *
     * @return the value of inspect_book_record.statement
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getStatement() {
        return statement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.statement
     *
     * @param statement the value for inspect_book_record.statement
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setStatement(String statement) {
        this.statement = statement == null ? null : statement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.scene_condition
     *
     * @return the value of inspect_book_record.scene_condition
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getSceneCondition() {
        return sceneCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.scene_condition
     *
     * @param sceneCondition the value for inspect_book_record.scene_condition
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setSceneCondition(String sceneCondition) {
        this.sceneCondition = sceneCondition == null ? null : sceneCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.first_enforcer
     *
     * @return the value of inspect_book_record.first_enforcer
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getFirstEnforcer() {
        return firstEnforcer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.first_enforcer
     *
     * @param firstEnforcer the value for inspect_book_record.first_enforcer
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setFirstEnforcer(String firstEnforcer) {
        this.firstEnforcer = firstEnforcer == null ? null : firstEnforcer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.second_enforcer
     *
     * @return the value of inspect_book_record.second_enforcer
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getSecondEnforcer() {
        return secondEnforcer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.second_enforcer
     *
     * @param secondEnforcer the value for inspect_book_record.second_enforcer
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setSecondEnforcer(String secondEnforcer) {
        this.secondEnforcer = secondEnforcer == null ? null : secondEnforcer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.recorder_time
     *
     * @return the value of inspect_book_record.recorder_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getRecorderTime() {
        return recorderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.recorder_time
     *
     * @param recorderTime the value for inspect_book_record.recorder_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setRecorderTime(Date recorderTime) {
        this.recorderTime = recorderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.operate_time
     *
     * @return the value of inspect_book_record.operate_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.operate_time
     *
     * @param operateTime the value for inspect_book_record.operate_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.operate_ip
     *
     * @return the value of inspect_book_record.operate_ip
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.operate_ip
     *
     * @param operateIp the value for inspect_book_record.operate_ip
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_record.operator
     *
     * @return the value of inspect_book_record.operator
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_record.operator
     *
     * @param operator the value for inspect_book_record.operator
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}