package com.example.upc.dataobject;

import java.util.Date;

public class InspectBookConf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_book_conf.id
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_book_conf.book_type
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    private Integer bookType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_book_conf.seq
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_book_conf.book_name
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_book_conf.book_url
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    private String bookUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_book_conf.operate_time
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_book_conf.operate_ip
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    private String operateIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_book_conf.operator
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_conf.id
     *
     * @return the value of inspect_book_conf.id
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_conf.id
     *
     * @param id the value for inspect_book_conf.id
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_conf.book_type
     *
     * @return the value of inspect_book_conf.book_type
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public Integer getBookType() {
        return bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_conf.book_type
     *
     * @param bookType the value for inspect_book_conf.book_type
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public void setBookType(Integer bookType) {
        this.bookType = bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_conf.seq
     *
     * @return the value of inspect_book_conf.seq
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_conf.seq
     *
     * @param seq the value for inspect_book_conf.seq
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_conf.book_name
     *
     * @return the value of inspect_book_conf.book_name
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_conf.book_name
     *
     * @param bookName the value for inspect_book_conf.book_name
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_conf.book_url
     *
     * @return the value of inspect_book_conf.book_url
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public String getBookUrl() {
        return bookUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_conf.book_url
     *
     * @param bookUrl the value for inspect_book_conf.book_url
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public void setBookUrl(String bookUrl) {
        this.bookUrl = bookUrl == null ? null : bookUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_conf.operate_time
     *
     * @return the value of inspect_book_conf.operate_time
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_conf.operate_time
     *
     * @param operateTime the value for inspect_book_conf.operate_time
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_conf.operate_ip
     *
     * @return the value of inspect_book_conf.operate_ip
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_conf.operate_ip
     *
     * @param operateIp the value for inspect_book_conf.operate_ip
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_book_conf.operator
     *
     * @return the value of inspect_book_conf.operator
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_book_conf.operator
     *
     * @param operator the value for inspect_book_conf.operator
     *
     * @mbg.generated Fri Jul 05 15:00:48 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}