package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import java.util.Date;

public class InspectRetificationNotice {
    private Integer id;
    private Integer parentId;
    private String fileNumber;
    @NotBlank(message = "当事人不能为空")
    private String concernedPerson;
    private String businessAddress;
    @NotBlank(message = "行为不能为空")
    private String behavior;
    @NotBlank(message = "违反规定不能为空")
    private String violationRegulations;
    private String accordingLaw;
    private String lawProvisions;
    private String lawTerm;
    private String lawItem;
    private String outdataPunishment;
    private String correctContent;
    private Date recorderDate;
    private Date completionDate;
    private String contacts;
    private String phoneNumber;
    private Date operateTime;
    private String operateIp;
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.id
     *
     * @return the value of inspect_retification_notice.id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.id
     *
     * @param id the value for inspect_retification_notice.id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.parent_id
     *
     * @return the value of inspect_retification_notice.parent_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.parent_id
     *
     * @param parentId the value for inspect_retification_notice.parent_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.file_number
     *
     * @return the value of inspect_retification_notice.file_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getFileNumber() {
        return fileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.file_number
     *
     * @param fileNumber the value for inspect_retification_notice.file_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setFileNumber(String fileNumber) {
        this.fileNumber = fileNumber == null ? null : fileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.concerned_person
     *
     * @return the value of inspect_retification_notice.concerned_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getConcernedPerson() {
        return concernedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.concerned_person
     *
     * @param concernedPerson the value for inspect_retification_notice.concerned_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setConcernedPerson(String concernedPerson) {
        this.concernedPerson = concernedPerson == null ? null : concernedPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.business_address
     *
     * @return the value of inspect_retification_notice.business_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getBusinessAddress() {
        return businessAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.business_address
     *
     * @param businessAddress the value for inspect_retification_notice.business_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setBusinessAddress(String businessAddress) {
        this.businessAddress = businessAddress == null ? null : businessAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.behavior
     *
     * @return the value of inspect_retification_notice.behavior
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.behavior
     *
     * @param behavior the value for inspect_retification_notice.behavior
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setBehavior(String behavior) {
        this.behavior = behavior == null ? null : behavior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.violation_regulations
     *
     * @return the value of inspect_retification_notice.violation_regulations
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getViolationRegulations() {
        return violationRegulations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.violation_regulations
     *
     * @param violationRegulations the value for inspect_retification_notice.violation_regulations
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setViolationRegulations(String violationRegulations) {
        this.violationRegulations = violationRegulations == null ? null : violationRegulations.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.according_law
     *
     * @return the value of inspect_retification_notice.according_law
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getAccordingLaw() {
        return accordingLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.according_law
     *
     * @param accordingLaw the value for inspect_retification_notice.according_law
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setAccordingLaw(String accordingLaw) {
        this.accordingLaw = accordingLaw == null ? null : accordingLaw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.law_provisions
     *
     * @return the value of inspect_retification_notice.law_provisions
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getLawProvisions() {
        return lawProvisions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.law_provisions
     *
     * @param lawProvisions the value for inspect_retification_notice.law_provisions
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setLawProvisions(String lawProvisions) {
        this.lawProvisions = lawProvisions == null ? null : lawProvisions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.law_term
     *
     * @return the value of inspect_retification_notice.law_term
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getLawTerm() {
        return lawTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.law_term
     *
     * @param lawTerm the value for inspect_retification_notice.law_term
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setLawTerm(String lawTerm) {
        this.lawTerm = lawTerm == null ? null : lawTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.law_item
     *
     * @return the value of inspect_retification_notice.law_item
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getLawItem() {
        return lawItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.law_item
     *
     * @param lawItem the value for inspect_retification_notice.law_item
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setLawItem(String lawItem) {
        this.lawItem = lawItem == null ? null : lawItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.outdata_punishment
     *
     * @return the value of inspect_retification_notice.outdata_punishment
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOutdataPunishment() {
        return outdataPunishment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.outdata_punishment
     *
     * @param outdataPunishment the value for inspect_retification_notice.outdata_punishment
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOutdataPunishment(String outdataPunishment) {
        this.outdataPunishment = outdataPunishment == null ? null : outdataPunishment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.correct_content
     *
     * @return the value of inspect_retification_notice.correct_content
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getCorrectContent() {
        return correctContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.correct_content
     *
     * @param correctContent the value for inspect_retification_notice.correct_content
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setCorrectContent(String correctContent) {
        this.correctContent = correctContent == null ? null : correctContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.recorder_date
     *
     * @return the value of inspect_retification_notice.recorder_date
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getRecorderDate() {
        return recorderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.recorder_date
     *
     * @param recorderDate the value for inspect_retification_notice.recorder_date
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setRecorderDate(Date recorderDate) {
        this.recorderDate = recorderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.completion_date
     *
     * @return the value of inspect_retification_notice.completion_date
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getCompletionDate() {
        return completionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.completion_date
     *
     * @param completionDate the value for inspect_retification_notice.completion_date
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setCompletionDate(Date completionDate) {
        this.completionDate = completionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.contacts
     *
     * @return the value of inspect_retification_notice.contacts
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.contacts
     *
     * @param contacts the value for inspect_retification_notice.contacts
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.phone_number
     *
     * @return the value of inspect_retification_notice.phone_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.phone_number
     *
     * @param phoneNumber the value for inspect_retification_notice.phone_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.operate_time
     *
     * @return the value of inspect_retification_notice.operate_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.operate_time
     *
     * @param operateTime the value for inspect_retification_notice.operate_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.operate_ip
     *
     * @return the value of inspect_retification_notice.operate_ip
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.operate_ip
     *
     * @param operateIp the value for inspect_retification_notice.operate_ip
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_retification_notice.operator
     *
     * @return the value of inspect_retification_notice.operator
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_retification_notice.operator
     *
     * @param operator the value for inspect_retification_notice.operator
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}