package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import java.util.Date;

public class InspectPlaceFinancialList {
    private Integer id;
    private Integer parentId;
    private String bookNumber;
    @NotBlank(message = ("当事人不能为空"))
    private String concernedPerson;
    private String businessAddress;
    private String firstExecutivePerson;
    private String secondExecutivePerson;
    private Date recordTime;
    private Date operateTime;
    private String operator;
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.id
     *
     * @return the value of inspect_place_financial_list.id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.id
     *
     * @param id the value for inspect_place_financial_list.id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.parent_id
     *
     * @return the value of inspect_place_financial_list.parent_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.parent_id
     *
     * @param parentId the value for inspect_place_financial_list.parent_id
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.book_number
     *
     * @return the value of inspect_place_financial_list.book_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getBookNumber() {
        return bookNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.book_number
     *
     * @param bookNumber the value for inspect_place_financial_list.book_number
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setBookNumber(String bookNumber) {
        this.bookNumber = bookNumber == null ? null : bookNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.concerned_person
     *
     * @return the value of inspect_place_financial_list.concerned_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getConcernedPerson() {
        return concernedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.concerned_person
     *
     * @param concernedPerson the value for inspect_place_financial_list.concerned_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setConcernedPerson(String concernedPerson) {
        this.concernedPerson = concernedPerson == null ? null : concernedPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.business_address
     *
     * @return the value of inspect_place_financial_list.business_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getBusinessAddress() {
        return businessAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.business_address
     *
     * @param businessAddress the value for inspect_place_financial_list.business_address
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setBusinessAddress(String businessAddress) {
        this.businessAddress = businessAddress == null ? null : businessAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.first_executive_person
     *
     * @return the value of inspect_place_financial_list.first_executive_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getFirstExecutivePerson() {
        return firstExecutivePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.first_executive_person
     *
     * @param firstExecutivePerson the value for inspect_place_financial_list.first_executive_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setFirstExecutivePerson(String firstExecutivePerson) {
        this.firstExecutivePerson = firstExecutivePerson == null ? null : firstExecutivePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.second_executive_person
     *
     * @return the value of inspect_place_financial_list.second_executive_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getSecondExecutivePerson() {
        return secondExecutivePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.second_executive_person
     *
     * @param secondExecutivePerson the value for inspect_place_financial_list.second_executive_person
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setSecondExecutivePerson(String secondExecutivePerson) {
        this.secondExecutivePerson = secondExecutivePerson == null ? null : secondExecutivePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.record_time
     *
     * @return the value of inspect_place_financial_list.record_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.record_time
     *
     * @param recordTime the value for inspect_place_financial_list.record_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.operate_time
     *
     * @return the value of inspect_place_financial_list.operate_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.operate_time
     *
     * @param operateTime the value for inspect_place_financial_list.operate_time
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.operator
     *
     * @return the value of inspect_place_financial_list.operator
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.operator
     *
     * @param operator the value for inspect_place_financial_list.operator
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_place_financial_list.operate_ip
     *
     * @return the value of inspect_place_financial_list.operate_ip
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_place_financial_list.operate_ip
     *
     * @param operateIp the value for inspect_place_financial_list.operate_ip
     *
     * @mbg.generated Fri Aug 30 21:03:34 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}