package com.example.upc.dataobject;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class MonthlySelfCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.id
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.enterprise_id
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.check_time
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.check_staff
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private String checkStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.accompany_staff
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private String accompanyStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.check_content
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private String checkContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.existed_problem
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private String existedProblem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.rectify_situation
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private String rectifySituation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.last_existed_problem
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private String lastExistedProblem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.operator
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.operator_ip
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_self_check.operator_time
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.id
     *
     * @return the value of monthly_self_check.id
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.id
     *
     * @param id the value for monthly_self_check.id
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.enterprise_id
     *
     * @return the value of monthly_self_check.enterprise_id
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.enterprise_id
     *
     * @param enterpriseId the value for monthly_self_check.enterprise_id
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.check_time
     *
     * @return the value of monthly_self_check.check_time
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.check_time
     *
     * @param checkTime the value for monthly_self_check.check_time
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.check_staff
     *
     * @return the value of monthly_self_check.check_staff
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public String getCheckStaff() {
        return checkStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.check_staff
     *
     * @param checkStaff the value for monthly_self_check.check_staff
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setCheckStaff(String checkStaff) {
        this.checkStaff = checkStaff == null ? null : checkStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.accompany_staff
     *
     * @return the value of monthly_self_check.accompany_staff
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public String getAccompanyStaff() {
        return accompanyStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.accompany_staff
     *
     * @param accompanyStaff the value for monthly_self_check.accompany_staff
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setAccompanyStaff(String accompanyStaff) {
        this.accompanyStaff = accompanyStaff == null ? null : accompanyStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.check_content
     *
     * @return the value of monthly_self_check.check_content
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public String getCheckContent() {
        return checkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.check_content
     *
     * @param checkContent the value for monthly_self_check.check_content
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setCheckContent(String checkContent) {
        this.checkContent = checkContent == null ? null : checkContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.existed_problem
     *
     * @return the value of monthly_self_check.existed_problem
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public String getExistedProblem() {
        return existedProblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.existed_problem
     *
     * @param existedProblem the value for monthly_self_check.existed_problem
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setExistedProblem(String existedProblem) {
        this.existedProblem = existedProblem == null ? null : existedProblem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.rectify_situation
     *
     * @return the value of monthly_self_check.rectify_situation
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public String getRectifySituation() {
        return rectifySituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.rectify_situation
     *
     * @param rectifySituation the value for monthly_self_check.rectify_situation
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setRectifySituation(String rectifySituation) {
        this.rectifySituation = rectifySituation == null ? null : rectifySituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.last_existed_problem
     *
     * @return the value of monthly_self_check.last_existed_problem
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public String getLastExistedProblem() {
        return lastExistedProblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.last_existed_problem
     *
     * @param lastExistedProblem the value for monthly_self_check.last_existed_problem
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setLastExistedProblem(String lastExistedProblem) {
        this.lastExistedProblem = lastExistedProblem == null ? null : lastExistedProblem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.operator
     *
     * @return the value of monthly_self_check.operator
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.operator
     *
     * @param operator the value for monthly_self_check.operator
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.operator_ip
     *
     * @return the value of monthly_self_check.operator_ip
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.operator_ip
     *
     * @param operatorIp the value for monthly_self_check.operator_ip
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_self_check.operator_time
     *
     * @return the value of monthly_self_check.operator_time
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_self_check.operator_time
     *
     * @param operatorTime the value for monthly_self_check.operator_time
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}