package com.example.upc.dataobject;

import java.util.Date;

public class MorningAttendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morning_attendance.id
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morning_attendance.enterprise_id
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morning_attendance.check_time
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morning_attendance.recorder_name
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    private String recorderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morning_attendance.operator
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morning_attendance.operator_ip
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morning_attendance.operator_time
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morning_attendance.id
     *
     * @return the value of morning_attendance.id
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morning_attendance.id
     *
     * @param id the value for morning_attendance.id
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morning_attendance.enterprise_id
     *
     * @return the value of morning_attendance.enterprise_id
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morning_attendance.enterprise_id
     *
     * @param enterpriseId the value for morning_attendance.enterprise_id
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morning_attendance.check_time
     *
     * @return the value of morning_attendance.check_time
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morning_attendance.check_time
     *
     * @param checkTime the value for morning_attendance.check_time
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morning_attendance.recorder_name
     *
     * @return the value of morning_attendance.recorder_name
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public String getRecorderName() {
        return recorderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morning_attendance.recorder_name
     *
     * @param recorderName the value for morning_attendance.recorder_name
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public void setRecorderName(String recorderName) {
        this.recorderName = recorderName == null ? null : recorderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morning_attendance.operator
     *
     * @return the value of morning_attendance.operator
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morning_attendance.operator
     *
     * @param operator the value for morning_attendance.operator
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morning_attendance.operator_ip
     *
     * @return the value of morning_attendance.operator_ip
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morning_attendance.operator_ip
     *
     * @param operatorIp the value for morning_attendance.operator_ip
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morning_attendance.operator_time
     *
     * @return the value of morning_attendance.operator_time
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morning_attendance.operator_time
     *
     * @param operatorTime the value for morning_attendance.operator_time
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}