package com.example.upc.dataobject;

import java.util.Date;

public class QuickCheckBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.id
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.date
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.check_name
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String checkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.check_company
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String checkCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.address
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.main_operation_type
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String mainOperationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.charger
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String charger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.phone
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.check_items
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String checkItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.check_result
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String checkResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.buy_money
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private Float buyMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.check_batch
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private Integer checkBatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.team
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.market
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.check_person
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String checkPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.check_product
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String checkProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.remark
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.document
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String document;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.state
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.operator
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.operator_ip
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quick_check_base.operator_time
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.id
     *
     * @return the value of quick_check_base.id
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.id
     *
     * @param id the value for quick_check_base.id
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.date
     *
     * @return the value of quick_check_base.date
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.date
     *
     * @param date the value for quick_check_base.date
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.check_name
     *
     * @return the value of quick_check_base.check_name
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getCheckName() {
        return checkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.check_name
     *
     * @param checkName the value for quick_check_base.check_name
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setCheckName(String checkName) {
        this.checkName = checkName == null ? null : checkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.check_company
     *
     * @return the value of quick_check_base.check_company
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getCheckCompany() {
        return checkCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.check_company
     *
     * @param checkCompany the value for quick_check_base.check_company
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setCheckCompany(String checkCompany) {
        this.checkCompany = checkCompany == null ? null : checkCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.address
     *
     * @return the value of quick_check_base.address
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.address
     *
     * @param address the value for quick_check_base.address
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.main_operation_type
     *
     * @return the value of quick_check_base.main_operation_type
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getMainOperationType() {
        return mainOperationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.main_operation_type
     *
     * @param mainOperationType the value for quick_check_base.main_operation_type
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setMainOperationType(String mainOperationType) {
        this.mainOperationType = mainOperationType == null ? null : mainOperationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.charger
     *
     * @return the value of quick_check_base.charger
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getCharger() {
        return charger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.charger
     *
     * @param charger the value for quick_check_base.charger
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setCharger(String charger) {
        this.charger = charger == null ? null : charger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.phone
     *
     * @return the value of quick_check_base.phone
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.phone
     *
     * @param phone the value for quick_check_base.phone
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.check_items
     *
     * @return the value of quick_check_base.check_items
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getCheckItems() {
        return checkItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.check_items
     *
     * @param checkItems the value for quick_check_base.check_items
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setCheckItems(String checkItems) {
        this.checkItems = checkItems == null ? null : checkItems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.check_result
     *
     * @return the value of quick_check_base.check_result
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.check_result
     *
     * @param checkResult the value for quick_check_base.check_result
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult == null ? null : checkResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.buy_money
     *
     * @return the value of quick_check_base.buy_money
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public Float getBuyMoney() {
        return buyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.buy_money
     *
     * @param buyMoney the value for quick_check_base.buy_money
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setBuyMoney(Float buyMoney) {
        this.buyMoney = buyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.check_batch
     *
     * @return the value of quick_check_base.check_batch
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public Integer getCheckBatch() {
        return checkBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.check_batch
     *
     * @param checkBatch the value for quick_check_base.check_batch
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setCheckBatch(Integer checkBatch) {
        this.checkBatch = checkBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.team
     *
     * @return the value of quick_check_base.team
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.team
     *
     * @param team the value for quick_check_base.team
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.market
     *
     * @return the value of quick_check_base.market
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.market
     *
     * @param market the value for quick_check_base.market
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.check_person
     *
     * @return the value of quick_check_base.check_person
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getCheckPerson() {
        return checkPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.check_person
     *
     * @param checkPerson the value for quick_check_base.check_person
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setCheckPerson(String checkPerson) {
        this.checkPerson = checkPerson == null ? null : checkPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.check_product
     *
     * @return the value of quick_check_base.check_product
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getCheckProduct() {
        return checkProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.check_product
     *
     * @param checkProduct the value for quick_check_base.check_product
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setCheckProduct(String checkProduct) {
        this.checkProduct = checkProduct == null ? null : checkProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.remark
     *
     * @return the value of quick_check_base.remark
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.remark
     *
     * @param remark the value for quick_check_base.remark
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.document
     *
     * @return the value of quick_check_base.document
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getDocument() {
        return document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.document
     *
     * @param document the value for quick_check_base.document
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setDocument(String document) {
        this.document = document == null ? null : document.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.state
     *
     * @return the value of quick_check_base.state
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.state
     *
     * @param state the value for quick_check_base.state
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.operator
     *
     * @return the value of quick_check_base.operator
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.operator
     *
     * @param operator the value for quick_check_base.operator
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.operator_ip
     *
     * @return the value of quick_check_base.operator_ip
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.operator_ip
     *
     * @param operatorIp the value for quick_check_base.operator_ip
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quick_check_base.operator_time
     *
     * @return the value of quick_check_base.operator_time
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quick_check_base.operator_time
     *
     * @param operatorTime the value for quick_check_base.operator_time
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}