package com.example.upc.dataobject;

import java.util.Date;

public class SpotCheckStepType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check_step_type.id
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check_step_type.type
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check_step_type.operator
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check_step_type.operator_ip
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check_step_type.operator_time
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check_step_type.id
     *
     * @return the value of spot_check_step_type.id
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check_step_type.id
     *
     * @param id the value for spot_check_step_type.id
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check_step_type.type
     *
     * @return the value of spot_check_step_type.type
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check_step_type.type
     *
     * @param type the value for spot_check_step_type.type
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check_step_type.operator
     *
     * @return the value of spot_check_step_type.operator
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check_step_type.operator
     *
     * @param operator the value for spot_check_step_type.operator
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check_step_type.operator_ip
     *
     * @return the value of spot_check_step_type.operator_ip
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check_step_type.operator_ip
     *
     * @param operatorIp the value for spot_check_step_type.operator_ip
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check_step_type.operator_time
     *
     * @return the value of spot_check_step_type.operator_time
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check_step_type.operator_time
     *
     * @param operatorTime the value for spot_check_step_type.operator_time
     *
     * @mbg.generated Thu Aug 08 16:04:33 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}