package com.example.upc.dataobject;

import java.util.Date;

public class SupervisionConfigSubclass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.parent_id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.name
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.code
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.seq
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.remark
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_subclass.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.id
     *
     * @return the value of supervision_config_subclass.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.id
     *
     * @param id the value for supervision_config_subclass.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.parent_id
     *
     * @return the value of supervision_config_subclass.parent_id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.parent_id
     *
     * @param parentId the value for supervision_config_subclass.parent_id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.name
     *
     * @return the value of supervision_config_subclass.name
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.name
     *
     * @param name the value for supervision_config_subclass.name
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.code
     *
     * @return the value of supervision_config_subclass.code
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.code
     *
     * @param code the value for supervision_config_subclass.code
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.seq
     *
     * @return the value of supervision_config_subclass.seq
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.seq
     *
     * @param seq the value for supervision_config_subclass.seq
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.remark
     *
     * @return the value of supervision_config_subclass.remark
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.remark
     *
     * @param remark the value for supervision_config_subclass.remark
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.operate_time
     *
     * @return the value of supervision_config_subclass.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.operate_time
     *
     * @param operateTime the value for supervision_config_subclass.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.operator
     *
     * @return the value of supervision_config_subclass.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.operator
     *
     * @param operator the value for supervision_config_subclass.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_subclass.operate_ip
     *
     * @return the value of supervision_config_subclass.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_subclass.operate_ip
     *
     * @param operateIp the value for supervision_config_subclass.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}