package com.example.upc.dataobject;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class SupervisionCaMorningCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca_morning_check.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca_morning_check.ca_id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Integer caId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca_morning_check.morningcheck_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date morningcheckTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca_morning_check.morningcheck_content
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String morningcheckContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca_morning_check.reason
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca_morning_check.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca_morning_check.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca_morning_check.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca_morning_check.id
     *
     * @return the value of supervision_ca_morning_check.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca_morning_check.id
     *
     * @param id the value for supervision_ca_morning_check.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca_morning_check.ca_id
     *
     * @return the value of supervision_ca_morning_check.ca_id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Integer getCaId() {
        return caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca_morning_check.ca_id
     *
     * @param caId the value for supervision_ca_morning_check.ca_id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setCaId(Integer caId) {
        this.caId = caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca_morning_check.morningcheck_time
     *
     * @return the value of supervision_ca_morning_check.morningcheck_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Date getMorningcheckTime() {
        return morningcheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca_morning_check.morningcheck_time
     *
     * @param morningcheckTime the value for supervision_ca_morning_check.morningcheck_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setMorningcheckTime(Date morningcheckTime) {
        this.morningcheckTime = morningcheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca_morning_check.morningcheck_content
     *
     * @return the value of supervision_ca_morning_check.morningcheck_content
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getMorningcheckContent() {
        return morningcheckContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca_morning_check.morningcheck_content
     *
     * @param morningcheckContent the value for supervision_ca_morning_check.morningcheck_content
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setMorningcheckContent(String morningcheckContent) {
        this.morningcheckContent = morningcheckContent == null ? null : morningcheckContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca_morning_check.reason
     *
     * @return the value of supervision_ca_morning_check.reason
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca_morning_check.reason
     *
     * @param reason the value for supervision_ca_morning_check.reason
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca_morning_check.operate_time
     *
     * @return the value of supervision_ca_morning_check.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca_morning_check.operate_time
     *
     * @param operateTime the value for supervision_ca_morning_check.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca_morning_check.operator
     *
     * @return the value of supervision_ca_morning_check.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca_morning_check.operator
     *
     * @param operator the value for supervision_ca_morning_check.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca_morning_check.operate_ip
     *
     * @return the value of supervision_ca_morning_check.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca_morning_check.operate_ip
     *
     * @param operateIp the value for supervision_ca_morning_check.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}