package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class SupervisionEnMedical {
    private Integer id;
    private Integer enterpriseId;
    @NotBlank(message = "登记号不能为空")
    private String registerNumber;
    private String superviseCategory;
    @NotBlank(message = "发证机关不能为空")
    private String lssueAuthority;
    @NotNull(message = "发证日期不能为空")
    private Date giveTime;
    @NotNull(message = "开始日期不能为空")
    private Date startTime;
    @NotNull(message = "结束日期不能为空")
    private Date endTime;
    private String medicalSubject;
    private String remark;
    private Date operateTime;
    private String operator;
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.id
     *
     * @return the value of supervision_en_medical.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.id
     *
     * @param id the value for supervision_en_medical.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.enterprise_id
     *
     * @return the value of supervision_en_medical.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.enterprise_id
     *
     * @param enterpriseId the value for supervision_en_medical.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.register_number
     *
     * @return the value of supervision_en_medical.register_number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getRegisterNumber() {
        return registerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.register_number
     *
     * @param registerNumber the value for supervision_en_medical.register_number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setRegisterNumber(String registerNumber) {
        this.registerNumber = registerNumber == null ? null : registerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.supervise_category
     *
     * @return the value of supervision_en_medical.supervise_category
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getSuperviseCategory() {
        return superviseCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.supervise_category
     *
     * @param superviseCategory the value for supervision_en_medical.supervise_category
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setSuperviseCategory(String superviseCategory) {
        this.superviseCategory = superviseCategory == null ? null : superviseCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.lssue_authority
     *
     * @return the value of supervision_en_medical.lssue_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getLssueAuthority() {
        return lssueAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.lssue_authority
     *
     * @param lssueAuthority the value for supervision_en_medical.lssue_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setLssueAuthority(String lssueAuthority) {
        this.lssueAuthority = lssueAuthority == null ? null : lssueAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.give_time
     *
     * @return the value of supervision_en_medical.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getGiveTime() {
        return giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.give_time
     *
     * @param giveTime the value for supervision_en_medical.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setGiveTime(Date giveTime) {
        this.giveTime = giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.start_time
     *
     * @return the value of supervision_en_medical.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.start_time
     *
     * @param startTime the value for supervision_en_medical.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.end_time
     *
     * @return the value of supervision_en_medical.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.end_time
     *
     * @param endTime the value for supervision_en_medical.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.medical_subject
     *
     * @return the value of supervision_en_medical.medical_subject
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getMedicalSubject() {
        return medicalSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.medical_subject
     *
     * @param medicalSubject the value for supervision_en_medical.medical_subject
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setMedicalSubject(String medicalSubject) {
        this.medicalSubject = medicalSubject == null ? null : medicalSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.remark
     *
     * @return the value of supervision_en_medical.remark
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.remark
     *
     * @param remark the value for supervision_en_medical.remark
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.operate_time
     *
     * @return the value of supervision_en_medical.operate_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.operate_time
     *
     * @param operateTime the value for supervision_en_medical.operate_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.operator
     *
     * @return the value of supervision_en_medical.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.operator
     *
     * @param operator the value for supervision_en_medical.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_medical.operate_ip
     *
     * @return the value of supervision_en_medical.operate_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_medical.operate_ip
     *
     * @param operateIp the value for supervision_en_medical.operate_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}