package com.example.upc.dataobject;

import java.util.Date;

public class SupervisionEnDrugsPro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.id
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.index_id
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private Integer indexId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.business_name
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String businessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.business_address
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String businessAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.enterprise_person
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String enterprisePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.quality_person
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String qualityPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.number
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.operation_mode
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String operationMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.business_scope
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String businessScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.give_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private Date giveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.start_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.end_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.license_authority
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String licenseAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.check_type
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String checkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.dynamic_grade
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String dynamicGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.year_assessment
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String yearAssessment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.patrol_frequency
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String patrolFrequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.enterprise_scale
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String enterpriseScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.operator
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.operator_ip
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_en_drugs_pro.operator_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.id
     *
     * @return the value of supervision_en_drugs_pro.id
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.id
     *
     * @param id the value for supervision_en_drugs_pro.id
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.index_id
     *
     * @return the value of supervision_en_drugs_pro.index_id
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.index_id
     *
     * @param indexId the value for supervision_en_drugs_pro.index_id
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.business_name
     *
     * @return the value of supervision_en_drugs_pro.business_name
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.business_name
     *
     * @param businessName the value for supervision_en_drugs_pro.business_name
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.business_address
     *
     * @return the value of supervision_en_drugs_pro.business_address
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getBusinessAddress() {
        return businessAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.business_address
     *
     * @param businessAddress the value for supervision_en_drugs_pro.business_address
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setBusinessAddress(String businessAddress) {
        this.businessAddress = businessAddress == null ? null : businessAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.enterprise_person
     *
     * @return the value of supervision_en_drugs_pro.enterprise_person
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getEnterprisePerson() {
        return enterprisePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.enterprise_person
     *
     * @param enterprisePerson the value for supervision_en_drugs_pro.enterprise_person
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setEnterprisePerson(String enterprisePerson) {
        this.enterprisePerson = enterprisePerson == null ? null : enterprisePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.quality_person
     *
     * @return the value of supervision_en_drugs_pro.quality_person
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getQualityPerson() {
        return qualityPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.quality_person
     *
     * @param qualityPerson the value for supervision_en_drugs_pro.quality_person
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setQualityPerson(String qualityPerson) {
        this.qualityPerson = qualityPerson == null ? null : qualityPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.number
     *
     * @return the value of supervision_en_drugs_pro.number
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.number
     *
     * @param number the value for supervision_en_drugs_pro.number
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.operation_mode
     *
     * @return the value of supervision_en_drugs_pro.operation_mode
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getOperationMode() {
        return operationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.operation_mode
     *
     * @param operationMode the value for supervision_en_drugs_pro.operation_mode
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setOperationMode(String operationMode) {
        this.operationMode = operationMode == null ? null : operationMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.business_scope
     *
     * @return the value of supervision_en_drugs_pro.business_scope
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.business_scope
     *
     * @param businessScope the value for supervision_en_drugs_pro.business_scope
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.give_time
     *
     * @return the value of supervision_en_drugs_pro.give_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public Date getGiveTime() {
        return giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.give_time
     *
     * @param giveTime the value for supervision_en_drugs_pro.give_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setGiveTime(Date giveTime) {
        this.giveTime = giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.start_time
     *
     * @return the value of supervision_en_drugs_pro.start_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.start_time
     *
     * @param startTime the value for supervision_en_drugs_pro.start_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.end_time
     *
     * @return the value of supervision_en_drugs_pro.end_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.end_time
     *
     * @param endTime the value for supervision_en_drugs_pro.end_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.license_authority
     *
     * @return the value of supervision_en_drugs_pro.license_authority
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getLicenseAuthority() {
        return licenseAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.license_authority
     *
     * @param licenseAuthority the value for supervision_en_drugs_pro.license_authority
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setLicenseAuthority(String licenseAuthority) {
        this.licenseAuthority = licenseAuthority == null ? null : licenseAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.check_type
     *
     * @return the value of supervision_en_drugs_pro.check_type
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.check_type
     *
     * @param checkType the value for supervision_en_drugs_pro.check_type
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setCheckType(String checkType) {
        this.checkType = checkType == null ? null : checkType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.dynamic_grade
     *
     * @return the value of supervision_en_drugs_pro.dynamic_grade
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getDynamicGrade() {
        return dynamicGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.dynamic_grade
     *
     * @param dynamicGrade the value for supervision_en_drugs_pro.dynamic_grade
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setDynamicGrade(String dynamicGrade) {
        this.dynamicGrade = dynamicGrade == null ? null : dynamicGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.year_assessment
     *
     * @return the value of supervision_en_drugs_pro.year_assessment
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getYearAssessment() {
        return yearAssessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.year_assessment
     *
     * @param yearAssessment the value for supervision_en_drugs_pro.year_assessment
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setYearAssessment(String yearAssessment) {
        this.yearAssessment = yearAssessment == null ? null : yearAssessment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.patrol_frequency
     *
     * @return the value of supervision_en_drugs_pro.patrol_frequency
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getPatrolFrequency() {
        return patrolFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.patrol_frequency
     *
     * @param patrolFrequency the value for supervision_en_drugs_pro.patrol_frequency
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setPatrolFrequency(String patrolFrequency) {
        this.patrolFrequency = patrolFrequency == null ? null : patrolFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.enterprise_scale
     *
     * @return the value of supervision_en_drugs_pro.enterprise_scale
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getEnterpriseScale() {
        return enterpriseScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.enterprise_scale
     *
     * @param enterpriseScale the value for supervision_en_drugs_pro.enterprise_scale
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setEnterpriseScale(String enterpriseScale) {
        this.enterpriseScale = enterpriseScale == null ? null : enterpriseScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.operator
     *
     * @return the value of supervision_en_drugs_pro.operator
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.operator
     *
     * @param operator the value for supervision_en_drugs_pro.operator
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.operator_ip
     *
     * @return the value of supervision_en_drugs_pro.operator_ip
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.operator_ip
     *
     * @param operatorIp the value for supervision_en_drugs_pro.operator_ip
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_pro.operator_time
     *
     * @return the value of supervision_en_drugs_pro.operator_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_pro.operator_time
     *
     * @param operatorTime the value for supervision_en_drugs_pro.operator_time
     *
     * @mbg.generated Thu Apr 23 00:08:45 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}