package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class SupervisionEnFoodCir {
    private Integer id;
    private Integer enterpriseId;
    private String legalPerson;
    private String creditCode;
    @NotBlank(message = "证号不能为空")
    private String number;
    private String registerAdress;
    private Integer bodyType;
    private String produceAddress;
    @NotBlank(message = "经营项目不能为空")
    private String businessProject;
    @NotBlank(message = "经营种类不能为空")
    private String businessType;
    @NotNull(message = "发证日期不能为空")
    private Date giveTime;
    @NotNull(message = "开始日期不能为空")
    private Date startTime;
    @NotNull(message = "结束日期不能为空")
    private Date endTime;
    private Float validityAge;
    private Integer copiesNumber;
    @NotBlank(message = "发证机关不能为空")
    private String licenseAuthority;
    private String lssuer;
    private String inspector;
    private String businessMode;
    private String remark;
    private Date operateTime;
    private String operator;
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.id
     *
     * @return the value of supervision_en_food_cir.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.id
     *
     * @param id the value for supervision_en_food_cir.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.enterprise_id
     *
     * @return the value of supervision_en_food_cir.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.enterprise_id
     *
     * @param enterpriseId the value for supervision_en_food_cir.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.legal_person
     *
     * @return the value of supervision_en_food_cir.legal_person
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.legal_person
     *
     * @param legalPerson the value for supervision_en_food_cir.legal_person
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.credit_code
     *
     * @return the value of supervision_en_food_cir.credit_code
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.credit_code
     *
     * @param creditCode the value for supervision_en_food_cir.credit_code
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.number
     *
     * @return the value of supervision_en_food_cir.number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.number
     *
     * @param number the value for supervision_en_food_cir.number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.register_adress
     *
     * @return the value of supervision_en_food_cir.register_adress
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getRegisterAdress() {
        return registerAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.register_adress
     *
     * @param registerAdress the value for supervision_en_food_cir.register_adress
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setRegisterAdress(String registerAdress) {
        this.registerAdress = registerAdress == null ? null : registerAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.body_type
     *
     * @return the value of supervision_en_food_cir.body_type
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getBodyType() {
        return bodyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.body_type
     *
     * @param bodyType the value for supervision_en_food_cir.body_type
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setBodyType(Integer bodyType) {
        this.bodyType = bodyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.produce_address
     *
     * @return the value of supervision_en_food_cir.produce_address
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getProduceAddress() {
        return produceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.produce_address
     *
     * @param produceAddress the value for supervision_en_food_cir.produce_address
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setProduceAddress(String produceAddress) {
        this.produceAddress = produceAddress == null ? null : produceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.business_project
     *
     * @return the value of supervision_en_food_cir.business_project
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getBusinessProject() {
        return businessProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.business_project
     *
     * @param businessProject the value for supervision_en_food_cir.business_project
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setBusinessProject(String businessProject) {
        this.businessProject = businessProject == null ? null : businessProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.business_type
     *
     * @return the value of supervision_en_food_cir.business_type
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.business_type
     *
     * @param businessType the value for supervision_en_food_cir.business_type
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.give_time
     *
     * @return the value of supervision_en_food_cir.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getGiveTime() {
        return giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.give_time
     *
     * @param giveTime the value for supervision_en_food_cir.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setGiveTime(Date giveTime) {
        this.giveTime = giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.start_time
     *
     * @return the value of supervision_en_food_cir.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.start_time
     *
     * @param startTime the value for supervision_en_food_cir.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.end_time
     *
     * @return the value of supervision_en_food_cir.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.end_time
     *
     * @param endTime the value for supervision_en_food_cir.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.validity_age
     *
     * @return the value of supervision_en_food_cir.validity_age
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Float getValidityAge() {
        return validityAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.validity_age
     *
     * @param validityAge the value for supervision_en_food_cir.validity_age
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setValidityAge(Float validityAge) {
        this.validityAge = validityAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.copies_number
     *
     * @return the value of supervision_en_food_cir.copies_number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getCopiesNumber() {
        return copiesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.copies_number
     *
     * @param copiesNumber the value for supervision_en_food_cir.copies_number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setCopiesNumber(Integer copiesNumber) {
        this.copiesNumber = copiesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.license_authority
     *
     * @return the value of supervision_en_food_cir.license_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getLicenseAuthority() {
        return licenseAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.license_authority
     *
     * @param licenseAuthority the value for supervision_en_food_cir.license_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setLicenseAuthority(String licenseAuthority) {
        this.licenseAuthority = licenseAuthority == null ? null : licenseAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.lssuer
     *
     * @return the value of supervision_en_food_cir.lssuer
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getLssuer() {
        return lssuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.lssuer
     *
     * @param lssuer the value for supervision_en_food_cir.lssuer
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setLssuer(String lssuer) {
        this.lssuer = lssuer == null ? null : lssuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.inspector
     *
     * @return the value of supervision_en_food_cir.inspector
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getInspector() {
        return inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.inspector
     *
     * @param inspector the value for supervision_en_food_cir.inspector
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setInspector(String inspector) {
        this.inspector = inspector == null ? null : inspector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.business_mode
     *
     * @return the value of supervision_en_food_cir.business_mode
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getBusinessMode() {
        return businessMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.business_mode
     *
     * @param businessMode the value for supervision_en_food_cir.business_mode
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setBusinessMode(String businessMode) {
        this.businessMode = businessMode == null ? null : businessMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.remark
     *
     * @return the value of supervision_en_food_cir.remark
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.remark
     *
     * @param remark the value for supervision_en_food_cir.remark
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.operate_time
     *
     * @return the value of supervision_en_food_cir.operate_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.operate_time
     *
     * @param operateTime the value for supervision_en_food_cir.operate_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.operator
     *
     * @return the value of supervision_en_food_cir.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.operator
     *
     * @param operator the value for supervision_en_food_cir.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_cir.operate_ip
     *
     * @return the value of supervision_en_food_cir.operate_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_cir.operate_ip
     *
     * @param operateIp the value for supervision_en_food_cir.operate_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}