package com.example.upc.dataobject;

import java.util.Date;

public class SupervisionConfigCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_category.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_category.name
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_category.code
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_category.seq
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_category.industry
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Integer industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_category.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_category.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_config_category.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_category.id
     *
     * @return the value of supervision_config_category.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_category.id
     *
     * @param id the value for supervision_config_category.id
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_category.name
     *
     * @return the value of supervision_config_category.name
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_category.name
     *
     * @param name the value for supervision_config_category.name
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_category.code
     *
     * @return the value of supervision_config_category.code
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_category.code
     *
     * @param code the value for supervision_config_category.code
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_category.seq
     *
     * @return the value of supervision_config_category.seq
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_category.seq
     *
     * @param seq the value for supervision_config_category.seq
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_category.industry
     *
     * @return the value of supervision_config_category.industry
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Integer getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_category.industry
     *
     * @param industry the value for supervision_config_category.industry
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_category.operate_time
     *
     * @return the value of supervision_config_category.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_category.operate_time
     *
     * @param operateTime the value for supervision_config_category.operate_time
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_category.operator
     *
     * @return the value of supervision_config_category.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_category.operator
     *
     * @param operator the value for supervision_config_category.operator
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_config_category.operate_ip
     *
     * @return the value of supervision_config_category.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_config_category.operate_ip
     *
     * @param operateIp the value for supervision_config_category.operate_ip
     *
     * @mbg.generated Wed Jun 26 15:37:47 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}