package com.example.upc.dataobject;

import java.util.Date;

public class SysArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.id
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.name
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.region_number
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private String regionNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.executive_number
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private String executiveNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.parent_id
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.seq
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.level
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.status
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.remark
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.operator
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.operate_time
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.operate_ip
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.id
     *
     * @return the value of sys_area.id
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.id
     *
     * @param id the value for sys_area.id
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.name
     *
     * @return the value of sys_area.name
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.name
     *
     * @param name the value for sys_area.name
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.region_number
     *
     * @return the value of sys_area.region_number
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public String getRegionNumber() {
        return regionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.region_number
     *
     * @param regionNumber the value for sys_area.region_number
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setRegionNumber(String regionNumber) {
        this.regionNumber = regionNumber == null ? null : regionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.executive_number
     *
     * @return the value of sys_area.executive_number
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public String getExecutiveNumber() {
        return executiveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.executive_number
     *
     * @param executiveNumber the value for sys_area.executive_number
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setExecutiveNumber(String executiveNumber) {
        this.executiveNumber = executiveNumber == null ? null : executiveNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.parent_id
     *
     * @return the value of sys_area.parent_id
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.parent_id
     *
     * @param parentId the value for sys_area.parent_id
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.seq
     *
     * @return the value of sys_area.seq
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.seq
     *
     * @param seq the value for sys_area.seq
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.level
     *
     * @return the value of sys_area.level
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.level
     *
     * @param level the value for sys_area.level
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.status
     *
     * @return the value of sys_area.status
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.status
     *
     * @param status the value for sys_area.status
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.remark
     *
     * @return the value of sys_area.remark
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.remark
     *
     * @param remark the value for sys_area.remark
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.operator
     *
     * @return the value of sys_area.operator
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.operator
     *
     * @param operator the value for sys_area.operator
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.operate_time
     *
     * @return the value of sys_area.operate_time
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.operate_time
     *
     * @param operateTime the value for sys_area.operate_time
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.operate_ip
     *
     * @return the value of sys_area.operate_ip
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.operate_ip
     *
     * @param operateIp the value for sys_area.operate_ip
     *
     * @mbg.generated Tue Jul 09 15:37:30 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}