package com.example.upc.dataobject;

import java.util.Date;

public class SysDeptArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_area.id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_area.dept_id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_area.area_id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_area.is_half
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    private Integer isHalf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_area.operate_ip
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    private String operateIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_area.operate_time
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_area.operator
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_area.id
     *
     * @return the value of sys_dept_area.id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_area.id
     *
     * @param id the value for sys_dept_area.id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_area.dept_id
     *
     * @return the value of sys_dept_area.dept_id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_area.dept_id
     *
     * @param deptId the value for sys_dept_area.dept_id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_area.area_id
     *
     * @return the value of sys_dept_area.area_id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_area.area_id
     *
     * @param areaId the value for sys_dept_area.area_id
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_area.is_half
     *
     * @return the value of sys_dept_area.is_half
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public Integer getIsHalf() {
        return isHalf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_area.is_half
     *
     * @param isHalf the value for sys_dept_area.is_half
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public void setIsHalf(Integer isHalf) {
        this.isHalf = isHalf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_area.operate_ip
     *
     * @return the value of sys_dept_area.operate_ip
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_area.operate_ip
     *
     * @param operateIp the value for sys_dept_area.operate_ip
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_area.operate_time
     *
     * @return the value of sys_dept_area.operate_time
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_area.operate_time
     *
     * @param operateTime the value for sys_dept_area.operate_time
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_area.operator
     *
     * @return the value of sys_dept_area.operator
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_area.operator
     *
     * @param operator the value for sys_dept_area.operator
     *
     * @mbg.generated Tue Jul 23 16:55:21 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}