package com.example.upc.dataobject;

import java.util.Date;

public class SysUserError {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_error.id
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_error.user_id
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_error.error
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    private Integer error;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_error.error_date
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    private Date errorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_error.id
     *
     * @return the value of sys_user_error.id
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_error.id
     *
     * @param id the value for sys_user_error.id
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_error.user_id
     *
     * @return the value of sys_user_error.user_id
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_error.user_id
     *
     * @param userId the value for sys_user_error.user_id
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_error.error
     *
     * @return the value of sys_user_error.error
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    public Integer getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_error.error
     *
     * @param error the value for sys_user_error.error
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    public void setError(Integer error) {
        this.error = error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_error.error_date
     *
     * @return the value of sys_user_error.error_date
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    public Date getErrorDate() {
        return errorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_error.error_date
     *
     * @param errorDate the value for sys_user_error.error_date
     *
     * @mbg.generated Wed Jun 10 22:52:23 CST 2020
     */
    public void setErrorDate(Date errorDate) {
        this.errorDate = errorDate;
    }
}