package com.example.upc.dataobject;

import java.util.Date;

public class SysWorkType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_work_type.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_work_type.industry_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer industryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_work_type.name
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_work_type.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_work_type.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_work_type.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_work_type.id
     *
     * @return the value of exam_work_type.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_work_type.id
     *
     * @param id the value for exam_work_type.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_work_type.industry_id
     *
     * @return the value of exam_work_type.industry_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_work_type.industry_id
     *
     * @param industryId the value for exam_work_type.industry_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_work_type.name
     *
     * @return the value of exam_work_type.name
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_work_type.name
     *
     * @param name the value for exam_work_type.name
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_work_type.operator
     *
     * @return the value of exam_work_type.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_work_type.operator
     *
     * @param operator the value for exam_work_type.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_work_type.operate_time
     *
     * @return the value of exam_work_type.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_work_type.operate_time
     *
     * @param operateTime the value for exam_work_type.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_work_type.operate_ip
     *
     * @return the value of exam_work_type.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_work_type.operate_ip
     *
     * @param operateIp the value for exam_work_type.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}