package com.example.upc.dataobject;

import java.util.Date;

public class UserEnterpriseVote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.enterprise_id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.user_id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.vote_1
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Float vote1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.vote_2
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Float vote2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.vote_3
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Float vote3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.vote_4
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Float vote4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.vote_5
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Float vote5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.average
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Float average;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.operation_time
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Date operationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_vote.dept
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    private Integer dept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.id
     *
     * @return the value of user_enterprise_vote.id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.id
     *
     * @param id the value for user_enterprise_vote.id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.enterprise_id
     *
     * @return the value of user_enterprise_vote.enterprise_id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.enterprise_id
     *
     * @param enterpriseId the value for user_enterprise_vote.enterprise_id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.user_id
     *
     * @return the value of user_enterprise_vote.user_id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.user_id
     *
     * @param userId the value for user_enterprise_vote.user_id
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.vote_1
     *
     * @return the value of user_enterprise_vote.vote_1
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Float getVote1() {
        return vote1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.vote_1
     *
     * @param vote1 the value for user_enterprise_vote.vote_1
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setVote1(Float vote1) {
        this.vote1 = vote1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.vote_2
     *
     * @return the value of user_enterprise_vote.vote_2
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Float getVote2() {
        return vote2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.vote_2
     *
     * @param vote2 the value for user_enterprise_vote.vote_2
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setVote2(Float vote2) {
        this.vote2 = vote2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.vote_3
     *
     * @return the value of user_enterprise_vote.vote_3
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Float getVote3() {
        return vote3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.vote_3
     *
     * @param vote3 the value for user_enterprise_vote.vote_3
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setVote3(Float vote3) {
        this.vote3 = vote3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.vote_4
     *
     * @return the value of user_enterprise_vote.vote_4
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Float getVote4() {
        return vote4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.vote_4
     *
     * @param vote4 the value for user_enterprise_vote.vote_4
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setVote4(Float vote4) {
        this.vote4 = vote4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.vote_5
     *
     * @return the value of user_enterprise_vote.vote_5
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Float getVote5() {
        return vote5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.vote_5
     *
     * @param vote5 the value for user_enterprise_vote.vote_5
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setVote5(Float vote5) {
        this.vote5 = vote5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.average
     *
     * @return the value of user_enterprise_vote.average
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Float getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.average
     *
     * @param average the value for user_enterprise_vote.average
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setAverage(Float average) {
        this.average = average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.operation_time
     *
     * @return the value of user_enterprise_vote.operation_time
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.operation_time
     *
     * @param operationTime the value for user_enterprise_vote.operation_time
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_vote.dept
     *
     * @return the value of user_enterprise_vote.dept
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public Integer getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_vote.dept
     *
     * @param dept the value for user_enterprise_vote.dept
     *
     * @mbg.generated Fri Oct 16 22:22:21 CST 2020
     */
    public void setDept(Integer dept) {
        this.dept = dept;
    }
}