package com.example.upc.dataobject;

import java.util.Date;

public class UserEnterpriseProblemRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_problem_record.id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_problem_record.problem_id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_problem_record.problem_name
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    private String problemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_problem_record.problem_vote_id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    private Integer problemVoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise_problem_record.operation_time
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    private Date operationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_problem_record.id
     *
     * @return the value of user_enterprise_problem_record.id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_problem_record.id
     *
     * @param id the value for user_enterprise_problem_record.id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_problem_record.problem_id
     *
     * @return the value of user_enterprise_problem_record.problem_id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_problem_record.problem_id
     *
     * @param problemId the value for user_enterprise_problem_record.problem_id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_problem_record.problem_name
     *
     * @return the value of user_enterprise_problem_record.problem_name
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public String getProblemName() {
        return problemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_problem_record.problem_name
     *
     * @param problemName the value for user_enterprise_problem_record.problem_name
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public void setProblemName(String problemName) {
        this.problemName = problemName == null ? null : problemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_problem_record.problem_vote_id
     *
     * @return the value of user_enterprise_problem_record.problem_vote_id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public Integer getProblemVoteId() {
        return problemVoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_problem_record.problem_vote_id
     *
     * @param problemVoteId the value for user_enterprise_problem_record.problem_vote_id
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public void setProblemVoteId(Integer problemVoteId) {
        this.problemVoteId = problemVoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise_problem_record.operation_time
     *
     * @return the value of user_enterprise_problem_record.operation_time
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise_problem_record.operation_time
     *
     * @param operationTime the value for user_enterprise_problem_record.operation_time
     *
     * @mbg.generated Sat Oct 17 09:06:56 CST 2020
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }
}