package com.example.upc.dataobject;

import java.util.Date;

public class VideoConfigEx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.id
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.parent_id
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.seq
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.position
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.number
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.channel_number
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private String channelNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.byte_type
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private String byteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.operator
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.operator_ip
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_config_ex.operator_time
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.id
     *
     * @return the value of video_config_ex.id
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.id
     *
     * @param id the value for video_config_ex.id
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.parent_id
     *
     * @return the value of video_config_ex.parent_id
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.parent_id
     *
     * @param parentId the value for video_config_ex.parent_id
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.seq
     *
     * @return the value of video_config_ex.seq
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.seq
     *
     * @param seq the value for video_config_ex.seq
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.position
     *
     * @return the value of video_config_ex.position
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.position
     *
     * @param position the value for video_config_ex.position
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.number
     *
     * @return the value of video_config_ex.number
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.number
     *
     * @param number the value for video_config_ex.number
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.channel_number
     *
     * @return the value of video_config_ex.channel_number
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public String getChannelNumber() {
        return channelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.channel_number
     *
     * @param channelNumber the value for video_config_ex.channel_number
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setChannelNumber(String channelNumber) {
        this.channelNumber = channelNumber == null ? null : channelNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.byte_type
     *
     * @return the value of video_config_ex.byte_type
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public String getByteType() {
        return byteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.byte_type
     *
     * @param byteType the value for video_config_ex.byte_type
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setByteType(String byteType) {
        this.byteType = byteType == null ? null : byteType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.operator
     *
     * @return the value of video_config_ex.operator
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.operator
     *
     * @param operator the value for video_config_ex.operator
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.operator_ip
     *
     * @return the value of video_config_ex.operator_ip
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.operator_ip
     *
     * @param operatorIp the value for video_config_ex.operator_ip
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_config_ex.operator_time
     *
     * @return the value of video_config_ex.operator_time
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_config_ex.operator_time
     *
     * @param operatorTime the value for video_config_ex.operator_time
     *
     * @mbg.generated Thu Oct 10 15:14:23 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}