package com.example.upc.dataobject;

import java.util.Date;

public class ViewFormatOriginRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.id
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.enterprise
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private Integer enterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.area
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.record_time
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.document
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private String document;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.operator
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.operator_ip
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.operator_time
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private Date operatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_format_origin_record.total
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    private Long total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.id
     *
     * @return the value of view_format_origin_record.id
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.id
     *
     * @param id the value for view_format_origin_record.id
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.enterprise
     *
     * @return the value of view_format_origin_record.enterprise
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public Integer getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.enterprise
     *
     * @param enterprise the value for view_format_origin_record.enterprise
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setEnterprise(Integer enterprise) {
        this.enterprise = enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.area
     *
     * @return the value of view_format_origin_record.area
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.area
     *
     * @param area the value for view_format_origin_record.area
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.record_time
     *
     * @return the value of view_format_origin_record.record_time
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.record_time
     *
     * @param recordTime the value for view_format_origin_record.record_time
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.document
     *
     * @return the value of view_format_origin_record.document
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public String getDocument() {
        return document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.document
     *
     * @param document the value for view_format_origin_record.document
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setDocument(String document) {
        this.document = document == null ? null : document.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.operator
     *
     * @return the value of view_format_origin_record.operator
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.operator
     *
     * @param operator the value for view_format_origin_record.operator
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.operator_ip
     *
     * @return the value of view_format_origin_record.operator_ip
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.operator_ip
     *
     * @param operatorIp the value for view_format_origin_record.operator_ip
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.operator_time
     *
     * @return the value of view_format_origin_record.operator_time
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.operator_time
     *
     * @param operatorTime the value for view_format_origin_record.operator_time
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_format_origin_record.total
     *
     * @return the value of view_format_origin_record.total
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_format_origin_record.total
     *
     * @param total the value for view_format_origin_record.total
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    public void setTotal(Long total) {
        this.total = total;
    }
}