package com.example.upc.dataobject;

import java.math.BigDecimal;

public class ViewQuickCheckMarketPercentResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_quick_check_market_percent_result.market
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_quick_check_market_percent_result.total
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_quick_check_market_percent_result.yes
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    private BigDecimal yes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_quick_check_market_percent_result.no
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    private BigDecimal no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_quick_check_market_percent_result.percent
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    private String percent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_quick_check_market_percent_result.market
     *
     * @return the value of view_quick_check_market_percent_result.market
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_quick_check_market_percent_result.market
     *
     * @param market the value for view_quick_check_market_percent_result.market
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_quick_check_market_percent_result.total
     *
     * @return the value of view_quick_check_market_percent_result.total
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_quick_check_market_percent_result.total
     *
     * @param total the value for view_quick_check_market_percent_result.total
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_quick_check_market_percent_result.yes
     *
     * @return the value of view_quick_check_market_percent_result.yes
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public BigDecimal getYes() {
        return yes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_quick_check_market_percent_result.yes
     *
     * @param yes the value for view_quick_check_market_percent_result.yes
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public void setYes(BigDecimal yes) {
        this.yes = yes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_quick_check_market_percent_result.no
     *
     * @return the value of view_quick_check_market_percent_result.no
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public BigDecimal getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_quick_check_market_percent_result.no
     *
     * @param no the value for view_quick_check_market_percent_result.no
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public void setNo(BigDecimal no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_quick_check_market_percent_result.percent
     *
     * @return the value of view_quick_check_market_percent_result.percent
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public String getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_quick_check_market_percent_result.percent
     *
     * @param percent the value for view_quick_check_market_percent_result.percent
     *
     * @mbg.generated Sat Aug 10 00:01:59 CST 2019
     */
    public void setPercent(String percent) {
        this.percent = percent == null ? null : percent.trim();
    }
}