package com.example.upc.dataobject;

public class ViewSupplierTotal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_supplier_total.total
     *
     * @mbg.generated Wed Aug 14 20:06:15 CST 2019
     */
    private Long total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_supplier_total.total
     *
     * @return the value of view_supplier_total.total
     *
     * @mbg.generated Wed Aug 14 20:06:15 CST 2019
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_supplier_total.total
     *
     * @param total the value for view_supplier_total.total
     *
     * @mbg.generated Wed Aug 14 20:06:15 CST 2019
     */
    public void setTotal(Long total) {
        this.total = total;
    }
}