package com.example.upc.dataobject;

public class ViewQuickCheckBuyTotal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_quick_check_buy_total.total
     *
     * @mbg.generated Tue Aug 13 11:37:16 CST 2019
     */
    private Double total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_quick_check_buy_total.total
     *
     * @return the value of view_quick_check_buy_total.total
     *
     * @mbg.generated Tue Aug 13 11:37:16 CST 2019
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_quick_check_buy_total.total
     *
     * @param total the value for view_quick_check_buy_total.total
     *
     * @mbg.generated Tue Aug 13 11:37:16 CST 2019
     */
    public void setTotal(Double total) {
        this.total = total;
    }
}