package com.example.upc.controller.param;

import java.util.Date;

public class ExamTopicBankParam {
    private Integer id;

    private String title;

    private Integer type;

    private String optionA;

    private String optionB;

    private String optionC;

    private String optionD;

    private String optionE;

    private String optionF;

    private String answer;

    private String analysis;

    private Float industry;

    private Integer workType;

    private String remark;

    private Date operateTime;

    private String operator;

    private String operateIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.title
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.type
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.option_a
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOptionA() {
        return optionA;
    }

    public void setOptionA(String optionA) {
        this.optionA = optionA;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.option_b
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOptionB() {
        return optionB;
    }

    public void setOptionB(String optionB) {
        this.optionB = optionB;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.option_c
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOptionC() {
        return optionC;
    }

    public void setOptionC(String optionC) {
        this.optionC = optionC;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.option_d
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOptionD() {
        return optionD;
    }

    public void setOptionD(String optionD) {
        this.optionD = optionD;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.option_e
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOptionE() {
        return optionE;
    }

    public void setOptionE(String optionE) {
        this.optionE = optionE;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.option_f
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOptionF() {
        return optionF;
    }

    public void setOptionF(String optionF) {
        this.optionF = optionF;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.answer
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.analysis
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getAnalysis() {
        return analysis;
    }

    public void setAnalysis(String analysis) {
        this.analysis = analysis;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.score
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Float getIndustry() {
        return industry;
    }

    public void setIndustry(Float industry) {
        this.industry = industry;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.status
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getWorkType() {
        return workType;
    }

    public void setWorkType(Integer workType) {
        this.workType = workType;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.remark
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_topic_bank.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp;
    }
}
