package com.example.upc.controller.param;

public class SupervisorParam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.id
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.unit
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.department
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.name
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.sex
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.duties
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String duties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.form
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String form;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.id_number
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.number
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.telephone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.office_phone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.mold
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String mold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.work_mobile_phone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String workMobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.type
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.operator
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.operator_ip
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supervisor.operator_time
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    private String operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.id
     *
     * @return the value of sys_supervisor.id
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.id
     *
     * @param id the value for sys_supervisor.id
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.unit
     *
     * @return the value of sys_supervisor.unit
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.unit
     *
     * @param unit the value for sys_supervisor.unit
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.department
     *
     * @return the value of sys_supervisor.department
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.department
     *
     * @param department the value for sys_supervisor.department
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.name
     *
     * @return the value of sys_supervisor.name
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.name
     *
     * @param name the value for sys_supervisor.name
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.sex
     *
     * @return the value of sys_supervisor.sex
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.sex
     *
     * @param sex the value for sys_supervisor.sex
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.duties
     *
     * @return the value of sys_supervisor.duties
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getDuties() {
        return duties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.duties
     *
     * @param duties the value for sys_supervisor.duties
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setDuties(String duties) {
        this.duties = duties == null ? null : duties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.form
     *
     * @return the value of sys_supervisor.form
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.form
     *
     * @param form the value for sys_supervisor.form
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setForm(String form) {
        this.form = form == null ? null : form.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.id_number
     *
     * @return the value of sys_supervisor.id_number
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.id_number
     *
     * @param idNumber the value for sys_supervisor.id_number
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.number
     *
     * @return the value of sys_supervisor.number
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.number
     *
     * @param number the value for sys_supervisor.number
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.telephone
     *
     * @return the value of sys_supervisor.telephone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.telephone
     *
     * @param telephone the value for sys_supervisor.telephone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.office_phone
     *
     * @return the value of sys_supervisor.office_phone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.office_phone
     *
     * @param officePhone the value for sys_supervisor.office_phone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.mold
     *
     * @return the value of sys_supervisor.mold
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getMold() {
        return mold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.mold
     *
     * @param mold the value for sys_supervisor.mold
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setMold(String mold) {
        this.mold = mold == null ? null : mold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.work_mobile_phone
     *
     * @return the value of sys_supervisor.work_mobile_phone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getWorkMobilePhone() {
        return workMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.work_mobile_phone
     *
     * @param workMobilePhone the value for sys_supervisor.work_mobile_phone
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setWorkMobilePhone(String workMobilePhone) {
        this.workMobilePhone = workMobilePhone == null ? null : workMobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.type
     *
     * @return the value of sys_supervisor.type
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.type
     *
     * @param type the value for sys_supervisor.type
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.operator
     *
     * @return the value of sys_supervisor.operator
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.operator
     *
     * @param operator the value for sys_supervisor.operator
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.operator_ip
     *
     * @return the value of sys_supervisor.operator_ip
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.operator_ip
     *
     * @param operatorIp the value for sys_supervisor.operator_ip
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supervisor.operator_time
     *
     * @return the value of sys_supervisor.operator_time
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public String getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supervisor.operator_time
     *
     * @param operatorTime the value for sys_supervisor.operator_time
     *
     * @mbg.generated Thu May 09 10:35:55 CST 2019
     */
    public void setOperatorTime(String operatorTime) {
        this.operatorTime = operatorTime;
    }
}
