package com.example.upc.dao;

import com.example.upc.controller.param.BillReportParam;
import com.example.upc.controller.searchParam.BillReportSearchParam;
import com.example.upc.dataobject.BillReport;
import com.example.upc.dataobject.Billdao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BillReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_report
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_report
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    int insert(BillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_report
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    int insertSelective(BillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_report
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    BillReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_report
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    int updateByPrimaryKeySelective(BillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_report
     *
     * @mbg.generated Wed Sep 16 10:42:05 CST 2020
     */
    int updateByPrimaryKey(BillReport record);

    List<BillReportParam> selectBillReport(@Param("billParam") BillReportSearchParam billReportSearchParam);

    List<BillReportParam> selectBillReportByBillList(@Param("billList") List<Integer> billList);
}