package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.dataobject.CaseFiling;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CaseFilingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_filing
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_filing
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    int insert(CaseFiling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_filing
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    int insertSelective(CaseFiling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_filing
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    CaseFiling selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_filing
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    int updateByPrimaryKeySelective(CaseFiling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_filing
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CaseFiling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_filing
     *
     * @mbg.generated Wed May 15 20:11:11 CST 2019
     */
    int updateByPrimaryKey(CaseFiling record);
    int countList();
    List<CaseFiling> getPage(@Param("page") PageQuery page);
}