package com.example.upc.dao;

import com.example.upc.controller.param.CommitteeCheckParam;
import com.example.upc.dataobject.CommitteeCheck;
import com.example.upc.dataobject.SysUser;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestBody;

import java.util.List;

public interface CommitteeCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    int insert(CommitteeCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    int insertSelective(CommitteeCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    CommitteeCheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    int updateByPrimaryKeySelective(CommitteeCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check
     *
     * @mbg.generated Tue Oct 13 16:31:13 CST 2020
     */
    int updateByPrimaryKey(CommitteeCheck record);

    List<CommitteeCheck> getByDate(@Param("committeeCheckParam") CommitteeCheckParam committeeCheckParam);

    void updateSign(@Param("committeeCheck") CommitteeCheck committeeCheck);
}