package com.example.upc.dao;

import com.example.upc.controller.param.CommitteeCheckOptAnswerWithTopic;
import com.example.upc.dataobject.CommitteeCheckOptAnswer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommitteeCheckOptAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check_opt_answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check_opt_answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int insert(CommitteeCheckOptAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check_opt_answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int insertSelective(CommitteeCheckOptAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check_opt_answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    CommitteeCheckOptAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check_opt_answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int updateByPrimaryKeySelective(CommitteeCheckOptAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_check_opt_answer
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int updateByPrimaryKey(CommitteeCheckOptAnswer record);

    List<CommitteeCheckOptAnswerWithTopic> getByCheckId(@Param("checkId") Integer checkId, @Param("id") Integer id);

    void deleteByCheckId(Integer id);


}