package com.example.upc.dao;

import com.example.upc.controller.param.CommitteCheckOptParam;
import com.example.upc.dataobject.CommitteCheckOptCategory;
import com.example.upc.dataobject.CommitteeCheck;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommitteCheckOptCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committe_check_opt_category
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committe_check_opt_category
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int insert(CommitteCheckOptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committe_check_opt_category
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int insertSelective(CommitteCheckOptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committe_check_opt_category
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    CommitteCheckOptCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committe_check_opt_category
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int updateByPrimaryKeySelective(CommitteCheckOptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committe_check_opt_category
     *
     * @mbg.generated Tue Oct 13 10:10:17 CST 2020
     */
    int updateByPrimaryKey(CommitteCheckOptCategory record);

    List<CommitteCheckOptCategory> getAll();

    List<CommitteCheckOptParam> selectAllOpt(@Param("committeeCheck") CommitteeCheck committeeCheck);
}