package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.ComplaintSearchParam;
import com.example.upc.dataobject.ComplaintProblemTypeTwo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComplaintProblemTypeTwoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_two
     *
     * @mbg.generated Tue Sep 10 10:50:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_two
     *
     * @mbg.generated Tue Sep 10 10:50:29 CST 2019
     */
    int insert(ComplaintProblemTypeTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_two
     *
     * @mbg.generated Tue Sep 10 10:50:29 CST 2019
     */
    int insertSelective(ComplaintProblemTypeTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_two
     *
     * @mbg.generated Tue Sep 10 10:50:29 CST 2019
     */
    ComplaintProblemTypeTwo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_two
     *
     * @mbg.generated Tue Sep 10 10:50:29 CST 2019
     */
    int updateByPrimaryKeySelective(ComplaintProblemTypeTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_two
     *
     * @mbg.generated Tue Sep 10 10:50:29 CST 2019
     */
    int updateByPrimaryKey(ComplaintProblemTypeTwo record);
    int countList(@Param("search") ComplaintSearchParam search);
    List<ComplaintProblemTypeTwo> getPage(@Param("page") PageQuery page,@Param("search") ComplaintSearchParam search);
    int countByType(@Param("Type") String Type, @Param("Id") Integer Id);
    List<ComplaintProblemTypeTwo> getListByOne(@Param("One") String One);
    List<ComplaintProblemTypeTwo> getPageList(@Param("search") ComplaintSearchParam search);
}