package com.example.upc.dao;

import com.example.upc.controller.param.ComplaintRecordListParam;
import com.example.upc.controller.param.ComplaintRecordParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.ComplaintRecordSearchParam;
import com.example.upc.dataobject.ComplaintRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComplaintRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_record
     *
     * @mbg.generated Fri Nov 15 21:56:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_record
     *
     * @mbg.generated Fri Nov 15 21:56:04 CST 2019
     */
    int insert(ComplaintRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_record
     *
     * @mbg.generated Fri Nov 15 21:56:04 CST 2019
     */
    int insertSelective(ComplaintRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_record
     *
     * @mbg.generated Fri Nov 15 21:56:04 CST 2019
     */
    ComplaintRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_record
     *
     * @mbg.generated Fri Nov 15 21:56:04 CST 2019
     */
    int updateByPrimaryKeySelective(ComplaintRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_record
     *
     * @mbg.generated Fri Nov 15 21:56:04 CST 2019
     */
    int updateByPrimaryKey(ComplaintRecord record);

    int countList(@Param("recordDept") Integer recordDept, @Param("dept") Integer dept, @Param("leader") Integer leader, @Param("recordPerson") String recordPerson, @Param("search") ComplaintRecordSearchParam search);
    List<ComplaintRecordParam> getPage(@Param("page") PageQuery page, @Param("recordDept") Integer recordDept, @Param("dept") Integer dept, @Param("leader") Integer leader, @Param("recordPerson") String recordPerson, @Param("search") ComplaintRecordSearchParam search);
    List<ComplaintRecordListParam> getListTypeNumberByDate(@Param("search") ComplaintRecordSearchParam complaintRecordSearchParam);
    List<ComplaintRecordListParam> getListTypeNumberByDateStep(@Param("search") ComplaintRecordSearchParam complaintRecordSearchParam);
    int countAllTotal(@Param("search") ComplaintRecordSearchParam complaintRecordSearchParam);
    int countDeptTotal(@Param("search") ComplaintRecordSearchParam complaintRecordSearchParam);
    List<ComplaintRecordListParam> getListTypeNumberByDateDept(@Param("search") ComplaintRecordSearchParam complaintRecordSearchParam);
    int countTotalAll();
    List<ComplaintRecordListParam> getListTypeNumberAll();
    ComplaintRecord getRecordById(@Param("id") Integer id);
    int countListAdmin(@Param("search") ComplaintRecordSearchParam search);
    List<ComplaintRecordParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") ComplaintRecordSearchParam search);
}