package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.ComplaintSearchParam;
import com.example.upc.dataobject.ComplaintEmergencyType;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComplaintEmergencyTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_emergency_type
     *
     * @mbg.generated Mon Sep 09 21:12:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_emergency_type
     *
     * @mbg.generated Mon Sep 09 21:12:55 CST 2019
     */
    int insert(ComplaintEmergencyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_emergency_type
     *
     * @mbg.generated Mon Sep 09 21:12:55 CST 2019
     */
    int insertSelective(ComplaintEmergencyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_emergency_type
     *
     * @mbg.generated Mon Sep 09 21:12:55 CST 2019
     */
    ComplaintEmergencyType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_emergency_type
     *
     * @mbg.generated Mon Sep 09 21:12:55 CST 2019
     */
    int updateByPrimaryKeySelective(ComplaintEmergencyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_emergency_type
     *
     * @mbg.generated Mon Sep 09 21:12:55 CST 2019
     */
    int updateByPrimaryKey(ComplaintEmergencyType record);
    int countList(@Param("search") ComplaintSearchParam search);
    List<ComplaintEmergencyType> getPage(@Param("page") PageQuery page,@Param("search") ComplaintSearchParam search);
    int countByType(@Param("Type") String Type, @Param("Id") Integer Id);
    List<ComplaintEmergencyType> getPageList(@Param("search") ComplaintSearchParam search);
}