package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.ComplaintSearchParam;
import com.example.upc.dataobject.ComplaintProblemTypeOne;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComplaintProblemTypeOneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_one
     *
     * @mbg.generated Tue Sep 10 09:02:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_one
     *
     * @mbg.generated Tue Sep 10 09:02:36 CST 2019
     */
    int insert(ComplaintProblemTypeOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_one
     *
     * @mbg.generated Tue Sep 10 09:02:36 CST 2019
     */
    int insertSelective(ComplaintProblemTypeOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_one
     *
     * @mbg.generated Tue Sep 10 09:02:36 CST 2019
     */
    ComplaintProblemTypeOne selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_one
     *
     * @mbg.generated Tue Sep 10 09:02:36 CST 2019
     */
    int updateByPrimaryKeySelective(ComplaintProblemTypeOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_problem_type_one
     *
     * @mbg.generated Tue Sep 10 09:02:36 CST 2019
     */
    int updateByPrimaryKey(ComplaintProblemTypeOne record);
    int countList(@Param("search") ComplaintSearchParam search);
    List<ComplaintProblemTypeOne> getPage(@Param("page") PageQuery page,@Param("search") ComplaintSearchParam search);
    int countByType(@Param("Type") String Type, @Param("Id") Integer Id);
    List<ComplaintProblemTypeOne> getPageList(@Param("search") ComplaintSearchParam search);
}