package com.example.upc.dao;

import com.example.upc.controller.param.ExamCaExamParam;
import com.example.upc.controller.param.ExamSubjectParam;
import com.example.upc.controller.searchParam.ExamSubjectSearchParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.dataobject.ExamSubject;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExamSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_subject
     *
     * @mbg.generated Sun Aug 23 14:09:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_subject
     *
     * @mbg.generated Sun Aug 23 14:09:39 CST 2020
     */
    int insert(ExamSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_subject
     *
     * @mbg.generated Sun Aug 23 14:09:39 CST 2020
     */
    int insertSelective(ExamSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_subject
     *
     * @mbg.generated Sun Aug 23 14:09:39 CST 2020
     */
    ExamSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_subject
     *
     * @mbg.generated Sun Aug 23 14:09:39 CST 2020
     */
    int updateByPrimaryKeySelective(ExamSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_subject
     *
     * @mbg.generated Sun Aug 23 14:09:39 CST 2020
     */
    int updateByPrimaryKey(ExamSubject record);

    int countList();
    List<ExamSubjectSearchParam> getPage(@Param("page") PageQuery page, @Param("search") ExamSubjectSearchParam examSubjectSearchParam);
    int countByIndustryAndWorkType(@Param("industry") int industry,@Param("workType") int workType);

    List<ExamSubjectParam> getByWorkType(@Param("workType") int workType);
}