package com.example.upc.dao;

import com.example.upc.controller.param.FoodAdditiveParam;
import com.example.upc.controller.searchParam.FoodAdditiveSearchParam;
import com.example.upc.dataobject.FoodAdditive;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FoodAdditiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_additive
     *
     * @mbg.generated Mon Sep 28 20:24:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_additive
     *
     * @mbg.generated Mon Sep 28 20:24:28 CST 2020
     */
    int insert(FoodAdditive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_additive
     *
     * @mbg.generated Mon Sep 28 20:24:28 CST 2020
     */
    int insertSelective(FoodAdditive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_additive
     *
     * @mbg.generated Mon Sep 28 20:24:28 CST 2020
     */
    FoodAdditive selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_additive
     *
     * @mbg.generated Mon Sep 28 20:24:28 CST 2020
     */
    int updateByPrimaryKeySelective(FoodAdditive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_additive
     *
     * @mbg.generated Mon Sep 28 20:24:28 CST 2020
     */
    int updateByPrimaryKey(FoodAdditive record);

    List<FoodAdditiveParam> selectByDate(@Param("foodParam") FoodAdditiveSearchParam foodAdditiveSearchParam);
}