package com.example.upc.dao;

import com.example.upc.controller.param.FormatPictureSupParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.PictureSearchParam;
import com.example.upc.controller.searchParam.WasteSearchParam;
import com.example.upc.dataobject.FormatPicture;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_picture
     *
     * @mbg.generated Tue Jul 23 20:51:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_picture
     *
     * @mbg.generated Tue Jul 23 20:51:39 CST 2019
     */
    int insert(FormatPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_picture
     *
     * @mbg.generated Tue Jul 23 20:51:39 CST 2019
     */
    int insertSelective(FormatPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_picture
     *
     * @mbg.generated Tue Jul 23 20:51:39 CST 2019
     */
    FormatPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_picture
     *
     * @mbg.generated Tue Jul 23 20:51:39 CST 2019
     */
    int updateByPrimaryKeySelective(FormatPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_picture
     *
     * @mbg.generated Tue Jul 23 20:51:39 CST 2019
     */
    int updateByPrimaryKey(FormatPicture record);
    int countList();
    int countListSup(@Param("search") PictureSearchParam search);
    List<FormatPictureSupParam> getPage(@Param("page") PageQuery page, @Param("search") PictureSearchParam search);
    int countListAdmin(@Param("search") PictureSearchParam search);
    List<FormatPictureSupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") PictureSearchParam search);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") PictureSearchParam search);
    List<FormatPicture> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") PictureSearchParam search);
    int countListByEnterpriseId(@Param("id") Integer id);
    List<FormatPictureSupParam> getPageByEnterpriseId(@Param("page") PageQuery page, @Param("id") Integer id);
    List<FormatPictureSupParam> getPageByEnterpriseId2(@Param("search") WasteSearchParam wasteSearchParam, @Param("id") Integer id);
}