package com.example.upc.dao;

import com.example.upc.controller.param.FormatAdditiveSupParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.AdditiveSearchParam;
import com.example.upc.dataobject.FormatAdditive;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatAdditiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_additive
     *
     * @mbg.generated Mon Jul 22 10:49:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_additive
     *
     * @mbg.generated Mon Jul 22 10:49:34 CST 2019
     */
    int insert(FormatAdditive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_additive
     *
     * @mbg.generated Mon Jul 22 10:49:34 CST 2019
     */
    int insertSelective(FormatAdditive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_additive
     *
     * @mbg.generated Mon Jul 22 10:49:34 CST 2019
     */
    FormatAdditive selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_additive
     *
     * @mbg.generated Mon Jul 22 10:49:34 CST 2019
     */
    int updateByPrimaryKeySelective(FormatAdditive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_additive
     *
     * @mbg.generated Mon Jul 22 10:49:34 CST 2019
     */
    int updateByPrimaryKey(FormatAdditive record);
    int countList();
    int countListSup(@Param("search") AdditiveSearchParam search);
    List<FormatAdditiveSupParam> getPage(@Param("page") PageQuery page, @Param("search") AdditiveSearchParam search);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") AdditiveSearchParam search);
    List<FormatAdditiveSupParam> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") AdditiveSearchParam search);
    int updateRecord(@Param("id") Integer id, @Param("publicity") String publicity);
    int countListAdmin(@Param("search") AdditiveSearchParam search);
    List<FormatAdditiveSupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") AdditiveSearchParam search);
}