package com.example.upc.dao;

import com.example.upc.controller.param.FormatGoodsSupParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.GoodsSearchParam;
import com.example.upc.dataobject.FormatGoods;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods
     *
     * @mbg.generated Wed Jul 24 14:48:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods
     *
     * @mbg.generated Wed Jul 24 14:48:48 CST 2019
     */
    int insert(FormatGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods
     *
     * @mbg.generated Wed Jul 24 14:48:48 CST 2019
     */
    int insertSelective(FormatGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods
     *
     * @mbg.generated Wed Jul 24 14:48:48 CST 2019
     */
    FormatGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods
     *
     * @mbg.generated Wed Jul 24 14:48:48 CST 2019
     */
    int updateByPrimaryKeySelective(FormatGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods
     *
     * @mbg.generated Wed Jul 24 14:48:48 CST 2019
     */
    int updateByPrimaryKey(FormatGoods record);
    int countList();
    int countListSup(@Param("search") GoodsSearchParam search);
    List<FormatGoodsSupParam> getPage(@Param("page") PageQuery page, @Param("search") GoodsSearchParam search);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") GoodsSearchParam search);
    List<FormatGoods> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") GoodsSearchParam search);
    int countByUnit(@Param("Unit") Integer Unit, @Param("Type") String Type,
                    @Param("Name") String Name, @Param("Supplier") String Supplier,
                    @Param("Brand") String Brand,@Param("id") Integer id );
    FormatGoods selectByUnit(@Param("Unit") Integer Unit, @Param("Type") String Type,
                             @Param("Name") String Name, @Param("Supplier") String Supplier,
                             @Param("Brand") String Brand);
    int updateByUnit(@Param("Unit") Integer Unit, @Param("Type") String Type,
                     @Param("Name") String Name, @Param("Supplier") String Supplier,
                     @Param("brand") String brand, @Param("num") Integer num);
}