package com.example.upc.dao;

import com.example.upc.controller.param.FormatDishesSupParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.DishSearchParam;
import com.example.upc.dataobject.FormatDishes;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatDishesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_dishes
     *
     * @mbg.generated Mon Jul 22 10:43:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_dishes
     *
     * @mbg.generated Mon Jul 22 10:43:47 CST 2019
     */
    int insert(FormatDishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_dishes
     *
     * @mbg.generated Mon Jul 22 10:43:47 CST 2019
     */
    int insertSelective(FormatDishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_dishes
     *
     * @mbg.generated Mon Jul 22 10:43:47 CST 2019
     */
    FormatDishes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_dishes
     *
     * @mbg.generated Mon Jul 22 10:43:47 CST 2019
     */
    int updateByPrimaryKeySelective(FormatDishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_dishes
     *
     * @mbg.generated Mon Jul 22 10:43:47 CST 2019
     */
    int updateByPrimaryKey(FormatDishes record);
    int countList();
    int countListSup(@Param("search") DishSearchParam search);
    List<FormatDishesSupParam> getPage(@Param("page") PageQuery page, @Param("search") DishSearchParam search);
    int countByName(@Param("Unit") Integer Unit, @Param("Area") Integer area, @Param("Name") String Name, @Param("Type") String Type, @Param("Id") Integer Id);
    int countByNumber(@Param("Unit") Integer Unit, @Param("Area") Integer area,@Param("Number") String Number, @Param("Id") Integer Id);
    int countByAll(@Param("Unit") Integer Unit, @Param("Area") Integer area, @Param("Name") String Name, @Param("Number") String Number, @Param("Type") String Type, @Param("Id") Integer Id);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") DishSearchParam search);
    List<FormatDishes> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") DishSearchParam search);
    int countListAdmin(@Param("search") DishSearchParam search);
    List<FormatDishesSupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") DishSearchParam search);
}