package com.example.upc.dao;

import com.example.upc.controller.param.FormatPartySupParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.PartySearchParam;
import com.example.upc.dataobject.FormatParty;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatPartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party
     *
     * @mbg.generated Tue Jul 23 19:44:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party
     *
     * @mbg.generated Tue Jul 23 19:44:59 CST 2019
     */
    int insert(FormatParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party
     *
     * @mbg.generated Tue Jul 23 19:44:59 CST 2019
     */
    int insertSelective(FormatParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party
     *
     * @mbg.generated Tue Jul 23 19:44:59 CST 2019
     */
    FormatParty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party
     *
     * @mbg.generated Tue Jul 23 19:44:59 CST 2019
     */
    int updateByPrimaryKeySelective(FormatParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party
     *
     * @mbg.generated Tue Jul 23 19:44:59 CST 2019
     */
    int updateByPrimaryKey(FormatParty record);
    int countList();
    int countListSup(@Param("search") PartySearchParam search);
    List<FormatPartySupParam> getPage(@Param("page") PageQuery page, @Param("search") PartySearchParam search);
    int countListAdmin(@Param("search") PartySearchParam search);
    List<FormatPartySupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") PartySearchParam search);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") PartySearchParam search);
    List<FormatParty> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") PartySearchParam search);
    int updateRecord(@Param("id") Integer id);
}