package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.TypeSearchParam;
import com.example.upc.dataobject.FormatOrigin;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatOriginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin
     *
     * @mbg.generated Fri Oct 18 17:09:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin
     *
     * @mbg.generated Fri Oct 18 17:09:59 CST 2019
     */
    int insert(FormatOrigin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin
     *
     * @mbg.generated Fri Oct 18 17:09:59 CST 2019
     */
    int insertSelective(FormatOrigin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin
     *
     * @mbg.generated Fri Oct 18 17:09:59 CST 2019
     */
    FormatOrigin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin
     *
     * @mbg.generated Fri Oct 18 17:09:59 CST 2019
     */
    int updateByPrimaryKeySelective(FormatOrigin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin
     *
     * @mbg.generated Fri Oct 18 17:09:59 CST 2019
     */
    int updateByPrimaryKey(FormatOrigin record);

    int countList(@Param("search") TypeSearchParam search);
    List<FormatOrigin> getPage(@Param("page") PageQuery page, @Param("search") TypeSearchParam search);
    int countByName(@Param("Type") String Type, @Param("Id") Integer Id);
}