package com.example.upc.dao;

import com.example.upc.controller.param.FormatPictureSupParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.PictureSearchParam;
import com.example.upc.dataobject.FormatEqup;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatEqupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_equp
     *
     * @mbg.generated Wed Nov 06 15:34:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_equp
     *
     * @mbg.generated Wed Nov 06 15:34:23 CST 2019
     */
    int insert(FormatEqup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_equp
     *
     * @mbg.generated Wed Nov 06 15:34:23 CST 2019
     */
    int insertSelective(FormatEqup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_equp
     *
     * @mbg.generated Wed Nov 06 15:34:23 CST 2019
     */
    FormatEqup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_equp
     *
     * @mbg.generated Wed Nov 06 15:34:23 CST 2019
     */
    int updateByPrimaryKeySelective(FormatEqup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_equp
     *
     * @mbg.generated Wed Nov 06 15:34:23 CST 2019
     */
    int updateByPrimaryKey(FormatEqup record);
    int countList();
    int countListSup(@Param("search") PictureSearchParam search);
    List<FormatPictureSupParam> getPage(@Param("page") PageQuery page, @Param("search") PictureSearchParam search);
    int countListAdmin(@Param("search") PictureSearchParam search);
    List<FormatPictureSupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") PictureSearchParam search);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") PictureSearchParam search);
    List<FormatEqup> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") PictureSearchParam search);
}