package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.SupplierSearchParam;
import com.example.upc.dataobject.FormatSupplier;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_supplier
     *
     * @mbg.generated Tue Oct 15 14:54:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_supplier
     *
     * @mbg.generated Tue Oct 15 14:54:50 CST 2019
     */
    int insert(FormatSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_supplier
     *
     * @mbg.generated Tue Oct 15 14:54:50 CST 2019
     */
    int insertSelective(FormatSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_supplier
     *
     * @mbg.generated Tue Oct 15 14:54:50 CST 2019
     */
    FormatSupplier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_supplier
     *
     * @mbg.generated Tue Oct 15 14:54:50 CST 2019
     */
    int updateByPrimaryKeySelective(FormatSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_supplier
     *
     * @mbg.generated Tue Oct 15 14:54:50 CST 2019
     */
    int updateByPrimaryKey(FormatSupplier record);
    int countList(@Param("search") SupplierSearchParam search, @Param("eid") Integer eid);
    List<FormatSupplier> getPage(@Param("page") PageQuery page, @Param("eid") Integer eid, @Param("search") SupplierSearchParam search);
    int countListSup(@Param("search") SupplierSearchParam search);
    List<FormatSupplier> getPageSup(@Param("page") PageQuery page, @Param("search") SupplierSearchParam search);
    int countListAdmin(@Param("search") SupplierSearchParam search);
    List<FormatSupplier> getPageAdmin(@Param("page") PageQuery page, @Param("search") SupplierSearchParam search);
    FormatSupplier selectByName(@Param("name") String name);
    FormatSupplier selectByInfo(@Param("eid") Integer eid, @Param("name") String name, @Param("type") String type);
    int countByAll(@Param("eid") Integer eid, @Param("stype") String stype, @Param("address") String address, @Param("name") String name,@Param("license") String license, @Param("number") String number,@Param("Id") Integer Id);
    List<FormatSupplier> getPage2( @Param("eid") Integer eid, @Param("search") SupplierSearchParam search);
}