package com.example.upc.dao;

import com.example.upc.controller.param.FormatGoodsSupParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.GoodsSearchParam;
import com.example.upc.dataobject.FormatGoodsOut;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatGoodsOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods_out
     *
     * @mbg.generated Mon Sep 02 18:18:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods_out
     *
     * @mbg.generated Mon Sep 02 18:18:23 CST 2019
     */
    int insert(FormatGoodsOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods_out
     *
     * @mbg.generated Mon Sep 02 18:18:23 CST 2019
     */
    int insertSelective(FormatGoodsOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods_out
     *
     * @mbg.generated Mon Sep 02 18:18:23 CST 2019
     */
    FormatGoodsOut selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods_out
     *
     * @mbg.generated Mon Sep 02 18:18:23 CST 2019
     */
    int updateByPrimaryKeySelective(FormatGoodsOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_goods_out
     *
     * @mbg.generated Mon Sep 02 18:18:23 CST 2019
     */
    int updateByPrimaryKey(FormatGoodsOut record);
    void batchInsert(@Param("formatGoodsOutList") List<FormatGoodsOut> formatGoodsOutList);
    void batchInsertEx(@Param("formatGoodsOutList") List<FormatGoodsOut> formatGoodsOutList);
    int countList(@Param("enterprise") Integer enterprise, @Param("search") GoodsSearchParam search);
    List<FormatGoodsOut> getPage(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") GoodsSearchParam search);
    int countListSup( @Param("search") GoodsSearchParam search);
    List<FormatGoodsSupParam> getPageSup(@Param("page") PageQuery page, @Param("search") GoodsSearchParam search);
    int countListAdmin( @Param("search") GoodsSearchParam search);
    List<FormatGoodsSupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") GoodsSearchParam search);

}