package com.example.upc.dao;

import com.example.upc.controller.param.FormatWasteSupParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.WasteSearchParam;
import com.example.upc.dataobject.FormatWaste;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatWasteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_waste
     *
     * @mbg.generated Tue Jul 23 22:05:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_waste
     *
     * @mbg.generated Tue Jul 23 22:05:04 CST 2019
     */
    int insert(FormatWaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_waste
     *
     * @mbg.generated Tue Jul 23 22:05:04 CST 2019
     */
    int insertSelective(FormatWaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_waste
     *
     * @mbg.generated Tue Jul 23 22:05:04 CST 2019
     */
    FormatWaste selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_waste
     *
     * @mbg.generated Tue Jul 23 22:05:04 CST 2019
     */
    int updateByPrimaryKeySelective(FormatWaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_waste
     *
     * @mbg.generated Tue Jul 23 22:05:04 CST 2019
     */
    int updateByPrimaryKey(FormatWaste record);
    int countList();
    int countListSup(@Param("search") WasteSearchParam wasteSearchParam);
    List<FormatWasteSupParam> getPage(@Param("page") PageQuery page, @Param("search") WasteSearchParam wasteSearchParam);
    int countListAdmin(@Param("search") WasteSearchParam wasteSearchParam);
    List<FormatWasteSupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") WasteSearchParam wasteSearchParam);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") WasteSearchParam wasteSearchParam);
    List<FormatWaste> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") WasteSearchParam wasteSearchParam);
    List<FormatWaste> getPageEnterprise2(@Param("enterprise") Integer enterprise, @Param("search") WasteSearchParam wasteSearchParam);

}