package com.example.upc.dao;

import com.example.upc.dataobject.FormatPartyConfig;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatPartyConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party_config
     *
     * @mbg.generated Tue Jul 09 21:56:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party_config
     *
     * @mbg.generated Tue Jul 09 21:56:55 CST 2019
     */
    int insert(FormatPartyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party_config
     *
     * @mbg.generated Tue Jul 09 21:56:55 CST 2019
     */
    int insertSelective(FormatPartyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party_config
     *
     * @mbg.generated Tue Jul 09 21:56:55 CST 2019
     */
    FormatPartyConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party_config
     *
     * @mbg.generated Tue Jul 09 21:56:55 CST 2019
     */
    int updateByPrimaryKeySelective(FormatPartyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_party_config
     *
     * @mbg.generated Tue Jul 09 21:56:55 CST 2019
     */
    int updateByPrimaryKey(FormatPartyConfig record);
    List<FormatPartyConfig> selectByParentId(@Param("id") int id);
    void deleteByParentId(@Param("parentId") int parentId);
    void batchInsert(@Param("formatPartyConfigList") List<FormatPartyConfig> formatPartyConfigList);
}