package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.MeasurementSearchParam;
import com.example.upc.dataobject.FormatMeasurement;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatMeasurementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_measurement
     *
     * @mbg.generated Thu Jul 25 15:15:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_measurement
     *
     * @mbg.generated Thu Jul 25 15:15:04 CST 2019
     */
    int insert(FormatMeasurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_measurement
     *
     * @mbg.generated Thu Jul 25 15:15:04 CST 2019
     */
    int insertSelective(FormatMeasurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_measurement
     *
     * @mbg.generated Thu Jul 25 15:15:04 CST 2019
     */
    FormatMeasurement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_measurement
     *
     * @mbg.generated Thu Jul 25 15:15:04 CST 2019
     */
    int updateByPrimaryKeySelective(FormatMeasurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_measurement
     *
     * @mbg.generated Thu Jul 25 15:15:04 CST 2019
     */
    int updateByPrimaryKey(FormatMeasurement record);
    int countList(@Param("search") MeasurementSearchParam measurementSearchParam);
    List<FormatMeasurement> getPage(@Param("page") PageQuery page, @Param("search") MeasurementSearchParam measurementSearchParam);
    int countByName(@Param("Name") String Name,@Param("Id") Integer Id);
}