package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.TypeSearchParam;
import com.example.upc.dataobject.FormatOriginFood;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatOriginFoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin_food
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin_food
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    int insert(FormatOriginFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin_food
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    int insertSelective(FormatOriginFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin_food
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    FormatOriginFood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin_food
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    int updateByPrimaryKeySelective(FormatOriginFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_origin_food
     *
     * @mbg.generated Fri Oct 18 15:33:30 CST 2019
     */
    int updateByPrimaryKey(FormatOriginFood record);

    int countList(@Param("search") TypeSearchParam search, @Param("id") Integer id);
    List<FormatOriginFood> getPage(@Param("page") PageQuery page, @Param("id") Integer id, @Param("search") TypeSearchParam search);
    int countByName(@Param("Type") String Type, @Param("Id") Integer Id);
}