package com.example.upc.dao;

import com.example.upc.dataobject.FormatLeaveSoup;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatLeaveSoupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_soup
     *
     * @mbg.generated Fri Sep 11 19:08:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_soup
     *
     * @mbg.generated Fri Sep 11 19:08:08 CST 2020
     */
    int insert(FormatLeaveSoup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_soup
     *
     * @mbg.generated Fri Sep 11 19:08:08 CST 2020
     */
    int insertSelective(FormatLeaveSoup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_soup
     *
     * @mbg.generated Fri Sep 11 19:08:08 CST 2020
     */
    FormatLeaveSoup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_soup
     *
     * @mbg.generated Fri Sep 11 19:08:08 CST 2020
     */
    int updateByPrimaryKeySelective(FormatLeaveSoup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_soup
     *
     * @mbg.generated Fri Sep 11 19:08:08 CST 2020
     */
    int updateByPrimaryKey(FormatLeaveSoup record);
    List<FormatLeaveSoup> selectByParentId(@Param("id") int id);
    void deleteByParentId(@Param("parentId") int parentId);
    void batchInsert(@Param("formatLeaveSoupList") List<FormatLeaveSoup> formatLeaveSoupList);
}