package com.example.upc.dao;

import com.example.upc.dataobject.GridPointsLocal;

public interface GridPointsLocalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_points_local
     *
     * @mbg.generated Sun Apr 05 17:10:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_points_local
     *
     * @mbg.generated Sun Apr 05 17:10:35 CST 2020
     */
    int insert(GridPointsLocal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_points_local
     *
     * @mbg.generated Sun Apr 05 17:10:35 CST 2020
     */
    int insertSelective(GridPointsLocal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_points_local
     *
     * @mbg.generated Sun Apr 05 17:10:35 CST 2020
     */
    GridPointsLocal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_points_local
     *
     * @mbg.generated Sun Apr 05 17:10:35 CST 2020
     */
    int updateByPrimaryKeySelective(GridPointsLocal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_points_local
     *
     * @mbg.generated Sun Apr 05 17:10:35 CST 2020
     */
    int updateByPrimaryKey(GridPointsLocal record);
}