package com.example.upc.dao;

import com.example.upc.dataobject.MiniFoodSamplesItem;

import java.util.List;

public interface MiniFoodSamplesItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_food_samples_item
     *
     * @mbg.generated Mon Aug 24 11:19:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_food_samples_item
     *
     * @mbg.generated Mon Aug 24 11:19:47 CST 2020
     */
    int insert(MiniFoodSamplesItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_food_samples_item
     *
     * @mbg.generated Mon Aug 24 11:19:47 CST 2020
     */
    int insertSelective(MiniFoodSamplesItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_food_samples_item
     *
     * @mbg.generated Mon Aug 24 11:19:47 CST 2020
     */
    MiniFoodSamplesItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_food_samples_item
     *
     * @mbg.generated Mon Aug 24 11:19:47 CST 2020
     */
    int updateByPrimaryKeySelective(MiniFoodSamplesItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_food_samples_item
     *
     * @mbg.generated Mon Aug 24 11:19:47 CST 2020
     */
    int updateByPrimaryKey(MiniFoodSamplesItem record);

    List<MiniFoodSamplesItem> selectByParentId(int parentId);
    int batchDelete(int parentId);
    int batchInsert(List<MiniFoodSamplesItem> miniFoodSamplesItems);
}