package com.example.upc.dao;

import com.example.upc.controller.param.MonthlySelfCheckParam;
import com.example.upc.controller.param.MonthlySelfcheckOptParam;
import com.example.upc.dataobject.ExamSubjectTopic;
import com.example.upc.dataobject.MonthlySelfcheckOptAnswer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MonthlySelfcheckOptAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_answer
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_answer
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int insert(MonthlySelfcheckOptAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_answer
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int insertSelective(MonthlySelfcheckOptAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_answer
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    MonthlySelfcheckOptAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_answer
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int updateByPrimaryKeySelective(MonthlySelfcheckOptAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_answer
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int updateByPrimaryKey(MonthlySelfcheckOptAnswer record);

    void batchInsert(@Param("optAnswerList") List<MonthlySelfcheckOptParam> OptAnswerList, @Param("selfCheckId") int selfCheckId);

    void deleteBySelfCheckId(@Param("selfCheckParam") MonthlySelfCheckParam monthlySelfCheckParam);

}