package com.example.upc.dao;

import com.example.upc.controller.param.FoodAdditiveParam;
import com.example.upc.controller.param.MonthlySelfCheckParam;
import com.example.upc.dataobject.MonthlySelfCheck;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface MonthlySelfCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_self_check
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_self_check
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    int insert(MonthlySelfCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_self_check
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    int insertSelective(MonthlySelfCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_self_check
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    MonthlySelfCheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_self_check
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    int updateByPrimaryKeySelective(MonthlySelfCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_self_check
     *
     * @mbg.generated Tue Oct 13 17:05:32 CST 2020
     */
    int updateByPrimaryKey(MonthlySelfCheck record);
    /**
     * 查询某一年的记录
     */
    List<MonthlySelfCheck> selectByDate(@Param("monthlySelfCheckParam") MonthlySelfCheckParam monthlySelfCheckParam);
    /**
     * 查询某一月的记录
     */
    MonthlySelfCheck selectByMonth(@Param("searchDate") Date date,@Param("enterpriseId") int enterpriseId);
}