package com.example.upc.dao;

import com.example.upc.controller.param.MonthlySelfCheckOptCategoryParam;
import com.example.upc.dataobject.MonthlySelfCheck;
import com.example.upc.dataobject.MonthlySelfcheckOptCategory;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MonthlySelfcheckOptCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_category
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_category
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int insert(MonthlySelfcheckOptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_category
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int insertSelective(MonthlySelfcheckOptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_category
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    MonthlySelfcheckOptCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_category
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int updateByPrimaryKeySelective(MonthlySelfcheckOptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_selfcheck_opt_category
     *
     * @mbg.generated Wed Oct 07 22:31:18 CST 2020
     */
    int updateByPrimaryKey(MonthlySelfcheckOptCategory record);

    List<MonthlySelfCheckOptCategoryParam> selectAllOpt(@Param("monthlySelfCheck") MonthlySelfCheck monthlySelfCheck);
}