package com.example.upc.dao;

import com.example.upc.controller.searchParam.MorningAttendanceSearchParam;
import com.example.upc.dataobject.MorningAttendance;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface MorningAttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table morning_attendance
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table morning_attendance
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    int insert(MorningAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table morning_attendance
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    int insertSelective(MorningAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table morning_attendance
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    MorningAttendance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table morning_attendance
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    int updateByPrimaryKeySelective(MorningAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table morning_attendance
     *
     * @mbg.generated Tue Oct 06 19:48:41 CST 2020
     */
    int updateByPrimaryKey(MorningAttendance record);

    List<MorningAttendance> getByEnterpriseMapper(@Param("infoId")Integer infoId);

    List<MorningAttendance> getMorningAttendanceByDate(@Param("enterpriseId")Integer enterpriseId, @Param("startDate")Date startDate, @Param("endDate")Date endDate);

    List<MorningAttendanceSearchParam> getMorningAttendanceSearchByDate(@Param("enterpriseId")Integer infoId,@Param("startDate") Date startDate, @Param("endDate")Date endDate);
}