package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.param.QuickCheckEnterpriseSupParam;
import com.example.upc.controller.searchParam.QuickCheckEnterpriseSearchParam;
import com.example.upc.dataobject.QuickCheckEnterprise;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface QuickCheckEnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int insert(QuickCheckEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int insertSelective(QuickCheckEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    QuickCheckEnterprise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int updateByPrimaryKeySelective(QuickCheckEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int updateByPrimaryKey(QuickCheckEnterprise record);
    int countListSup(@Param("search") QuickCheckEnterpriseSearchParam search);
    List<QuickCheckEnterpriseSupParam> getPage(@Param("page") PageQuery page, @Param("search") QuickCheckEnterpriseSearchParam search);
    int countListEnterprise(@Param("id") Integer id);
    List<QuickCheckEnterpriseSupParam> getPageEnterprise(@Param("page") PageQuery page, @Param("id") Integer id);
    int countListOk();
    List<QuickCheckEnterprise> getPageOk(@Param("page") PageQuery page);
    QuickCheckEnterprise getUser(@Param("id") Integer id);
    int check(@Param("id") Integer id);
}