package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.QuickCheckBaseSearchParam;
import com.example.upc.dataobject.QuickCheckBase;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface QuickCheckBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_base
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_base
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    int insert(QuickCheckBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_base
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    int insertSelective(QuickCheckBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_base
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    QuickCheckBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_base
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    int updateByPrimaryKeySelective(QuickCheckBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quick_check_base
     *
     * @mbg.generated Mon Aug 05 15:21:30 CST 2019
     */
    int updateByPrimaryKey(QuickCheckBase record);
    int countListSup(@Param("team") String team, @Param("search") QuickCheckBaseSearchParam quickCheckBaseSearchParam);
    List<QuickCheckBase> getPageSup(@Param("page") PageQuery page, @Param("team") String team, @Param("search") QuickCheckBaseSearchParam quickCheckBaseSearchParam);
    int countListEnterprise(@Param("market") String market, @Param("search") QuickCheckBaseSearchParam quickCheckBaseSearchParam);
    List<QuickCheckBase> getPageEnterprise(@Param("page") PageQuery page, @Param("market") String market, @Param("search") QuickCheckBaseSearchParam quickCheckBaseSearchParam);
    int countListAdmin(@Param("search") QuickCheckBaseSearchParam quickCheckBaseSearchParam);
    List<QuickCheckBase> getPageAdmin(@Param("page") PageQuery page, @Param("search") QuickCheckBaseSearchParam quickCheckBaseSearchParam);
    int updateRecord(@Param("id") Integer id);
    void batchInsert(@Param("quickCheckBaseList") List<QuickCheckBase> quickCheckBaseList);
}