package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.MeasurementSearchParam;
import com.example.upc.dataobject.SpecialEquipmentTypeOne;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SpecialEquipmentTypeOneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_one
     *
     * @mbg.generated Mon Oct 21 19:01:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_one
     *
     * @mbg.generated Mon Oct 21 19:01:40 CST 2019
     */
    int insert(SpecialEquipmentTypeOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_one
     *
     * @mbg.generated Mon Oct 21 19:01:40 CST 2019
     */
    int insertSelective(SpecialEquipmentTypeOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_one
     *
     * @mbg.generated Mon Oct 21 19:01:40 CST 2019
     */
    SpecialEquipmentTypeOne selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_one
     *
     * @mbg.generated Mon Oct 21 19:01:40 CST 2019
     */
    int updateByPrimaryKeySelective(SpecialEquipmentTypeOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_one
     *
     * @mbg.generated Mon Oct 21 19:01:40 CST 2019
     */
    int updateByPrimaryKey(SpecialEquipmentTypeOne record);

    int countList(@Param("search") MeasurementSearchParam search);
    List<SpecialEquipmentTypeOne> getPage(@Param("page") PageQuery page, @Param("search") MeasurementSearchParam search);
    int countByName(@Param("Name") String Name,@Param("Id") Integer Id);
}