package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.MeasurementSearchParam;
import com.example.upc.dataobject.SpecialEquipmentTypeThree;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SpecialEquipmentTypeThreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_three
     *
     * @mbg.generated Mon Oct 21 20:16:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_three
     *
     * @mbg.generated Mon Oct 21 20:16:20 CST 2019
     */
    int insert(SpecialEquipmentTypeThree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_three
     *
     * @mbg.generated Mon Oct 21 20:16:20 CST 2019
     */
    int insertSelective(SpecialEquipmentTypeThree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_three
     *
     * @mbg.generated Mon Oct 21 20:16:20 CST 2019
     */
    SpecialEquipmentTypeThree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_three
     *
     * @mbg.generated Mon Oct 21 20:16:20 CST 2019
     */
    int updateByPrimaryKeySelective(SpecialEquipmentTypeThree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_equipment_type_three
     *
     * @mbg.generated Mon Oct 21 20:16:20 CST 2019
     */
    int updateByPrimaryKey(SpecialEquipmentTypeThree record);

    int countList(@Param("search") MeasurementSearchParam search);
    List<SpecialEquipmentTypeThree> getPage(@Param("page") PageQuery page, @Param("search") MeasurementSearchParam search);
    int countListByParent(@Param("parent") String parent, @Param("search") MeasurementSearchParam search);
    List<SpecialEquipmentTypeThree> getPageByParent(@Param("page") PageQuery page, @Param("parent") String parent, @Param("search") MeasurementSearchParam search);
    int countByName(@Param("Parent") String Parent, @Param("Name") String Name,@Param("Id") Integer Id);
}