package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.dataobject.SpotCheckDisposalType;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SpotCheckDisposalTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_disposal_type
     *
     * @mbg.generated Tue Jul 30 10:51:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_disposal_type
     *
     * @mbg.generated Tue Jul 30 10:51:18 CST 2019
     */
    int insert(SpotCheckDisposalType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_disposal_type
     *
     * @mbg.generated Tue Jul 30 10:51:18 CST 2019
     */
    int insertSelective(SpotCheckDisposalType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_disposal_type
     *
     * @mbg.generated Tue Jul 30 10:51:18 CST 2019
     */
    SpotCheckDisposalType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_disposal_type
     *
     * @mbg.generated Tue Jul 30 10:51:18 CST 2019
     */
    int updateByPrimaryKeySelective(SpotCheckDisposalType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_disposal_type
     *
     * @mbg.generated Tue Jul 30 10:51:18 CST 2019
     */
    int updateByPrimaryKey(SpotCheckDisposalType record);
    int countList();
    List<SpotCheckDisposalType> getPage(@Param("page") PageQuery page);
    int countByType(@Param("Type") String Type, @Param("Id") Integer Id);
}