package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.param.SpotCheckEnterpriseSupParam;
import com.example.upc.controller.searchParam.SpotCheckEnterpriseSearchParam;
import com.example.upc.dataobject.SpotCheckEnterprise;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SpotCheckEnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int insert(SpotCheckEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int insertSelective(SpotCheckEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    SpotCheckEnterprise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int updateByPrimaryKeySelective(SpotCheckEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_enterprise
     *
     * @mbg.generated Thu Aug 01 16:50:41 CST 2019
     */
    int updateByPrimaryKey(SpotCheckEnterprise record);
    int countListSup(@Param("search") SpotCheckEnterpriseSearchParam search);
    List<SpotCheckEnterpriseSupParam> getPage(@Param("page") PageQuery page, @Param("search") SpotCheckEnterpriseSearchParam search);
    int countListEnterprise(@Param("id") Integer id);
    List<SpotCheckEnterpriseSupParam> getPageEnterprise(@Param("page") PageQuery page, @Param("id") Integer id);
    int countListOk();
    List<SpotCheckEnterprise> getPageOk(@Param("page") PageQuery page);
    SpotCheckEnterprise getUser(@Param("id") Integer id);
    int check(@Param("id") Integer id);
    int countListAdmin(@Param("search") SpotCheckEnterpriseSearchParam search);
    List<SpotCheckEnterpriseSupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") SpotCheckEnterpriseSearchParam search);
}