package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.dataobject.SpotCheckCheckType;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SpotCheckCheckTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_check_type
     *
     * @mbg.generated Mon Jul 29 17:24:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_check_type
     *
     * @mbg.generated Mon Jul 29 17:24:16 CST 2019
     */
    int insert(SpotCheckCheckType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_check_type
     *
     * @mbg.generated Mon Jul 29 17:24:16 CST 2019
     */
    int insertSelective(SpotCheckCheckType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_check_type
     *
     * @mbg.generated Mon Jul 29 17:24:16 CST 2019
     */
    SpotCheckCheckType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_check_type
     *
     * @mbg.generated Mon Jul 29 17:24:16 CST 2019
     */
    int updateByPrimaryKeySelective(SpotCheckCheckType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check_check_type
     *
     * @mbg.generated Mon Jul 29 17:24:16 CST 2019
     */
    int updateByPrimaryKey(SpotCheckCheckType record);
    int countList();
    List<SpotCheckCheckType> getPage(@Param("page") PageQuery page);
    int countByType(@Param("Type") String Type, @Param("Id") Integer Id);
}