package com.example.upc.dao;

import com.example.upc.dataobject.SupervisionEnMedicalBuIndex;
import com.example.upc.dataobject.SupervisionEnMedicalProIndex;
import com.example.upc.dataobject.SupervisionEnSmallCaterIndex;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SupervisionEnMedicalProIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_medical_pro_index
     *
     * @mbg.generated Fri Apr 24 17:22:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_medical_pro_index
     *
     * @mbg.generated Fri Apr 24 17:22:25 CST 2020
     */
    int insert(SupervisionEnMedicalProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_medical_pro_index
     *
     * @mbg.generated Fri Apr 24 17:22:25 CST 2020
     */
    int insertSelective(SupervisionEnMedicalProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_medical_pro_index
     *
     * @mbg.generated Fri Apr 24 17:22:25 CST 2020
     */
    SupervisionEnMedicalProIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_medical_pro_index
     *
     * @mbg.generated Fri Apr 24 17:22:25 CST 2020
     */
    int updateByPrimaryKeySelective(SupervisionEnMedicalProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_medical_pro_index
     *
     * @mbg.generated Fri Apr 24 17:22:25 CST 2020
     */
    int updateByPrimaryKey(SupervisionEnMedicalProIndex record);

    SupervisionEnMedicalProIndex selectByEnterpriseId(@Param("eid") Integer eid);
    List<SupervisionEnMedicalProIndex> getAll();
    int deleteByEnterpriseId(@Param("eid") Integer eid);
}