package com.example.upc.dao;

import com.example.upc.dataobject.SupervisionEnDrugsProIndex;
import com.example.upc.dataobject.SupervisionEnFoodBuIndex;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SupervisionEnFoodBuIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_bu_index
     *
     * @mbg.generated Mon Apr 20 22:56:34 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_bu_index
     *
     * @mbg.generated Mon Apr 20 22:56:34 CST 2020
     */
    int insert(SupervisionEnFoodBuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_bu_index
     *
     * @mbg.generated Mon Apr 20 22:56:34 CST 2020
     */
    int insertSelective(SupervisionEnFoodBuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_bu_index
     *
     * @mbg.generated Mon Apr 20 22:56:34 CST 2020
     */
    SupervisionEnFoodBuIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_bu_index
     *
     * @mbg.generated Mon Apr 20 22:56:34 CST 2020
     */
    int updateByPrimaryKeySelective(SupervisionEnFoodBuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_bu_index
     *
     * @mbg.generated Mon Apr 20 22:56:34 CST 2020
     */
    int updateByPrimaryKey(SupervisionEnFoodBuIndex record);

    SupervisionEnFoodBuIndex selectByEnterpriseId(@Param("eid") Integer eid);

    List<SupervisionEnFoodBuIndex> getAll();
    int deleteByEnterpriseId(@Param("eid") Integer eid);
}