package com.example.upc.dao;

import com.example.upc.dataobject.SupervisionEnCosmeticsIndex;
import com.example.upc.dataobject.SupervisionEnDrugsBuIndex;
import com.example.upc.dataobject.SupervisionEnDrugsProIndex;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SupervisionEnDrugsBuIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_bu_index
     *
     * @mbg.generated Thu Apr 23 00:08:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_bu_index
     *
     * @mbg.generated Thu Apr 23 00:08:01 CST 2020
     */
    int insert(SupervisionEnDrugsBuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_bu_index
     *
     * @mbg.generated Thu Apr 23 00:08:01 CST 2020
     */
    int insertSelective(SupervisionEnDrugsBuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_bu_index
     *
     * @mbg.generated Thu Apr 23 00:08:01 CST 2020
     */
    SupervisionEnDrugsBuIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_bu_index
     *
     * @mbg.generated Thu Apr 23 00:08:01 CST 2020
     */
    int updateByPrimaryKeySelective(SupervisionEnDrugsBuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_bu_index
     *
     * @mbg.generated Thu Apr 23 00:08:01 CST 2020
     */
    int updateByPrimaryKey(SupervisionEnDrugsBuIndex record);

    SupervisionEnDrugsBuIndex selectByEnterpriseId(@Param("eid") Integer eid);
    List<SupervisionEnDrugsBuIndex> getAll();
    int deleteByEnterpriseId(@Param("eid") Integer eid);
}