package com.example.upc.dao;

import com.example.upc.dataobject.SupervisionEnFoodBuIndex;
import com.example.upc.dataobject.SupervisionEnFoodProIndex;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SupervisionEnFoodProIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_pro_index
     *
     * @mbg.generated Fri Apr 24 16:29:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_pro_index
     *
     * @mbg.generated Fri Apr 24 16:29:53 CST 2020
     */
    int insert(SupervisionEnFoodProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_pro_index
     *
     * @mbg.generated Fri Apr 24 16:29:53 CST 2020
     */
    int insertSelective(SupervisionEnFoodProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_pro_index
     *
     * @mbg.generated Fri Apr 24 16:29:53 CST 2020
     */
    SupervisionEnFoodProIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_pro_index
     *
     * @mbg.generated Fri Apr 24 16:29:53 CST 2020
     */
    int updateByPrimaryKeySelective(SupervisionEnFoodProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_food_pro_index
     *
     * @mbg.generated Fri Apr 24 16:29:53 CST 2020
     */
    int updateByPrimaryKey(SupervisionEnFoodProIndex record);

    SupervisionEnFoodProIndex selectByEnterpriseId(@Param("eid") Integer eid);
    List<SupervisionEnFoodProIndex> getAll();
    int deleteByEnterpriseId(@Param("eid") Integer eid);
}