package com.example.upc.dao;

import com.example.upc.dataobject.SupervisionEnDrugsBuIndex;
import com.example.upc.dataobject.SupervisionEnDrugsProIndex;
import com.example.upc.dataobject.SupervisionEnIndustrialProductsIndex;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SupervisionEnDrugsProIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_pro_index
     *
     * @mbg.generated Thu Apr 23 00:08:29 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_pro_index
     *
     * @mbg.generated Thu Apr 23 00:08:29 CST 2020
     */
    int insert(SupervisionEnDrugsProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_pro_index
     *
     * @mbg.generated Thu Apr 23 00:08:29 CST 2020
     */
    int insertSelective(SupervisionEnDrugsProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_pro_index
     *
     * @mbg.generated Thu Apr 23 00:08:29 CST 2020
     */
    SupervisionEnDrugsProIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_pro_index
     *
     * @mbg.generated Thu Apr 23 00:08:29 CST 2020
     */
    int updateByPrimaryKeySelective(SupervisionEnDrugsProIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervision_en_drugs_pro_index
     *
     * @mbg.generated Thu Apr 23 00:08:29 CST 2020
     */
    int updateByPrimaryKey(SupervisionEnDrugsProIndex record);

    SupervisionEnDrugsProIndex selectByEnterpriseId(@Param("eid") Integer eid);
    List<SupervisionEnDrugsProIndex> getAll();
    int deleteByEnterpriseId(@Param("eid") Integer eid);
}