package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.dataobject.SysMaterialData;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysMaterialDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_material_data
     *
     * @mbg.generated Sat May 11 15:43:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_material_data
     *
     * @mbg.generated Sat May 11 15:43:06 CST 2019
     */
    int insert(SysMaterialData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_material_data
     *
     * @mbg.generated Sat May 11 15:43:06 CST 2019
     */
    int insertSelective(SysMaterialData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_material_data
     *
     * @mbg.generated Sat May 11 15:43:06 CST 2019
     */
    SysMaterialData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_material_data
     *
     * @mbg.generated Sat May 11 15:43:06 CST 2019
     */
    int updateByPrimaryKeySelective(SysMaterialData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_material_data
     *
     * @mbg.generated Sat May 11 15:43:06 CST 2019
     */
    int updateByPrimaryKey(SysMaterialData record);
    int countList();
    List<SysMaterialData> getPage(@Param("page") PageQuery page);
}