package com.example.upc.dao;

import com.example.upc.controller.param.NewsParam;
import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.NewsSearchParam;
import com.example.upc.dataobject.SysNews;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbg.generated Tue Oct 01 19:53:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbg.generated Tue Oct 01 19:53:52 CST 2019
     */
    int insert(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbg.generated Tue Oct 01 19:53:52 CST 2019
     */
    int insertSelective(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbg.generated Tue Oct 01 19:53:52 CST 2019
     */
    SysNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbg.generated Tue Oct 01 19:53:52 CST 2019
     */
    int updateByPrimaryKeySelective(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbg.generated Tue Oct 01 19:53:52 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbg.generated Tue Oct 01 19:53:52 CST 2019
     */
    int updateByPrimaryKey(SysNews record);

    int countList(@Param("id") Integer id,@Param("search") NewsSearchParam search);
    List<NewsParam> getPage(@Param("page") PageQuery page, @Param("id") Integer id,@Param("search") NewsSearchParam search);
    int countListAndroid(@Param("type") Integer type,@Param("search") NewsSearchParam search);
    List<NewsParam> getPageAndroid(@Param("page") PageQuery page, @Param("type") Integer type,@Param("search") NewsSearchParam search);
    int changeStatus(@Param("id")Integer id,@Param("status")Integer status);
    NewsParam selectById(@Param("id")Integer id);
}