package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.VideoSearchParam;
import com.example.upc.dataobject.VideoParent;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VideoParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_parent
     *
     * @mbg.generated Mon Nov 04 15:15:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_parent
     *
     * @mbg.generated Mon Nov 04 15:15:35 CST 2019
     */
    int insert(VideoParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_parent
     *
     * @mbg.generated Mon Nov 04 15:15:35 CST 2019
     */
    int insertSelective(VideoParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_parent
     *
     * @mbg.generated Mon Nov 04 15:15:35 CST 2019
     */
    VideoParent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_parent
     *
     * @mbg.generated Mon Nov 04 15:15:35 CST 2019
     */
    int updateByPrimaryKeySelective(VideoParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_parent
     *
     * @mbg.generated Mon Nov 04 15:15:35 CST 2019
     */
    int updateByPrimaryKey(VideoParent record);

    int countListSup(@Param("search") VideoSearchParam search);
    List<VideoParent> getPageSup(@Param("page") PageQuery page, @Param("search") VideoSearchParam search);
    int countListAdmin(@Param("search") VideoSearchParam search);
    List<VideoParent> getPageAdmin(@Param("page") PageQuery page, @Param("search") VideoSearchParam search);
    int countById(@Param("eid") Integer eid, @Param("Id") Integer Id);
    Integer selectByEnterpriseId(@Param("eid") Integer eid);
}