package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.param.VideoRecordEnterpriseParam;
import com.example.upc.controller.searchParam.VideoSearchParam;
import com.example.upc.dataobject.VideoRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VideoRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_record
     *
     * @mbg.generated Thu Oct 10 22:16:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_record
     *
     * @mbg.generated Thu Oct 10 22:16:12 CST 2019
     */
    int insert(VideoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_record
     *
     * @mbg.generated Thu Oct 10 22:16:12 CST 2019
     */
    int insertSelective(VideoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_record
     *
     * @mbg.generated Thu Oct 10 22:16:12 CST 2019
     */
    VideoRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_record
     *
     * @mbg.generated Thu Oct 10 22:16:12 CST 2019
     */
    int updateByPrimaryKeySelective(VideoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_record
     *
     * @mbg.generated Thu Oct 10 22:16:12 CST 2019
     */
    int updateByPrimaryKey(VideoRecord record);

    int countListSup(@Param("search") VideoSearchParam search);
    List<VideoRecord> getPageSup(@Param("page") PageQuery page, @Param("search") VideoSearchParam search);
    int countListAdmin(@Param("search") VideoSearchParam search);
    List<VideoRecord> getPageAdmin(@Param("page") PageQuery page, @Param("search") VideoSearchParam search);
    int countListLookSup(@Param("search") VideoSearchParam search);
    List<VideoRecordEnterpriseParam> getPageLookSup(@Param("page") PageQuery page, @Param("search") VideoSearchParam search);
    int countListLookAdmin(@Param("search") VideoSearchParam search);
    List<VideoRecordEnterpriseParam> getPageLookAdmin(@Param("page") PageQuery page, @Param("search") VideoSearchParam search);
    int countListLookByEnterpriseId(@Param("id") Integer id);
    List<VideoRecord> getPageLookByEnterpriseId(@Param("page") PageQuery page, @Param("id") Integer id);
    int countRecord(@Param("enterpriseId") int enterpriseId, @Param("id") Integer id);
    VideoRecord getRecordById(@Param("id") Integer id);
}