package com.example.upc.dao;

import com.example.upc.dataobject.ViewSpotCheckTeamResult;

import java.util.List;

public interface ViewSpotCheckTeamResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_spot_check_team_result
     *
     * @mbg.generated Fri Aug 09 10:21:02 CST 2019
     */
    int insert(ViewSpotCheckTeamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_spot_check_team_result
     *
     * @mbg.generated Fri Aug 09 10:21:02 CST 2019
     */
    int insertSelective(ViewSpotCheckTeamResult record);
    List<ViewSpotCheckTeamResult> getListAll();
}