package com.example.upc.dao;

import com.example.upc.dataobject.ViewQuickCheckTeamNameMoneyTotalResult;
import com.example.upc.dataobject.ViewQuickCheckTeamTypeNameMoneyTotalResult;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ViewQuickCheckTeamTypeNameMoneyTotalResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_quick_check_team_type_name_money_total_result
     *
     * @mbg.generated Fri Aug 09 23:20:48 CST 2019
     */
    int insert(ViewQuickCheckTeamTypeNameMoneyTotalResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_quick_check_team_type_name_money_total_result
     *
     * @mbg.generated Fri Aug 09 23:20:48 CST 2019
     */
    int insertSelective(ViewQuickCheckTeamTypeNameMoneyTotalResult record);
    List<ViewQuickCheckTeamNameMoneyTotalResult> getListByTeamTopTen(@Param("team") String team);
    List<ViewQuickCheckTeamNameMoneyTotalResult> getListByTypeTopTen(@Param("type") String type);
    List<ViewQuickCheckTeamNameMoneyTotalResult> getListByMarketTopTen(@Param("market") String market);
}