package com.example.upc.dao;

import com.example.upc.dataobject.ViewSpotCheckTypeResult;

import java.util.List;

public interface ViewSpotCheckTypeResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_spot_check_type_result
     *
     * @mbg.generated Fri Aug 09 11:04:42 CST 2019
     */
    int insert(ViewSpotCheckTypeResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_spot_check_type_result
     *
     * @mbg.generated Fri Aug 09 11:04:42 CST 2019
     */
    int insertSelective(ViewSpotCheckTypeResult record);
    List<ViewSpotCheckTypeResult> getListAll();
}