package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.EnterpriseRegulatorSearchParam;
import com.example.upc.dataobject.ViewSpotCheckEnterpriseTeamResult;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ViewSpotCheckEnterpriseTeamResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_spot_check_enterprise_team_result
     *
     * @mbg.generated Wed Aug 14 13:41:11 CST 2019
     */
    int insert(ViewSpotCheckEnterpriseTeamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_spot_check_enterprise_team_result
     *
     * @mbg.generated Wed Aug 14 13:41:11 CST 2019
     */
    int insertSelective(ViewSpotCheckEnterpriseTeamResult record);
    int countList(@Param("search") EnterpriseRegulatorSearchParam search);
    List<ViewSpotCheckEnterpriseTeamResult> getPage(@Param("page") PageQuery page, @Param("search") EnterpriseRegulatorSearchParam search);
}