package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.param.ViewFormatOriginRecordSupParam;
import com.example.upc.controller.searchParam.OriginRecordSearchParam;
import com.example.upc.dataobject.ViewFormatOriginRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ViewFormatOriginRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_format_origin_record
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    int insert(ViewFormatOriginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_format_origin_record
     *
     * @mbg.generated Fri Aug 02 18:35:48 CST 2019
     */
    int insertSelective(ViewFormatOriginRecord record);
    int countListSup(@Param("search") OriginRecordSearchParam search);
    List<ViewFormatOriginRecordSupParam> getPage(@Param("page") PageQuery page, @Param("search") OriginRecordSearchParam search);
    int countListAdmin(@Param("search") OriginRecordSearchParam search);
    List<ViewFormatOriginRecordSupParam> getPageAdmin(@Param("page") PageQuery page, @Param("search") OriginRecordSearchParam search);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") OriginRecordSearchParam search);
    List<ViewFormatOriginRecord> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") OriginRecordSearchParam search);
}