package com.example.upc.dao;

import com.example.upc.controller.param.PageQuery;
import com.example.upc.controller.searchParam.GoodsSearchParam;
import com.example.upc.dataobject.ViewFormatGoods;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ViewFormatGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_format_goods
     *
     * @mbg.generated Fri Jul 26 15:30:38 CST 2019
     */
    int insert(ViewFormatGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_format_goods
     *
     * @mbg.generated Fri Jul 26 15:30:38 CST 2019
     */
    int insertSelective(ViewFormatGoods record);
    int countList();
    int countListSup(@Param("search") GoodsSearchParam search);
    List<ViewFormatGoods> getPage(@Param("page") PageQuery page, @Param("search") GoodsSearchParam search);
    int countListAdmin(@Param("search") GoodsSearchParam search);
    List<ViewFormatGoods> getPageAdmin(@Param("page") PageQuery page, @Param("search") GoodsSearchParam search);
    int countListEnterprise(@Param("enterprise") Integer enterprise, @Param("search") GoodsSearchParam search);
    List<ViewFormatGoods> getPageEnterprise(@Param("page") PageQuery page, @Param("enterprise") Integer enterprise, @Param("search") GoodsSearchParam search);
    ViewFormatGoods selectByUnit(@Param("Unit") Integer Unit, @Param("Type") String Type,
                 @Param("Name") String Name, @Param("Supplier") String Supplier,
                 @Param("Brand") String Brand);
}