package com.example.upc.dao;

import com.example.upc.dataobject.ViewTeamEnterprisePercentResult;

import java.util.List;

public interface ViewTeamEnterprisePercentResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_team_enterprise_percent_result
     *
     * @mbg.generated Wed Aug 14 20:04:26 CST 2019
     */
    int insert(ViewTeamEnterprisePercentResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_team_enterprise_percent_result
     *
     * @mbg.generated Wed Aug 14 20:04:26 CST 2019
     */
    int insertSelective(ViewTeamEnterprisePercentResult record);
    List<ViewTeamEnterprisePercentResult> getListAll();
}